import $ from 'jquery';
import './styles.scss';
import {dataSets,categories} from './data.js';
import {escapeHTML as e,safeURL,findById,filterHeroes,filterRecords,heroFiltersFromParams,heroProfessions,heroFactions,compareSelection,detailTargetFromHash,searchDatabase,effectIdsForHero,effectsForTeam,heroesForBuilding,recipesForIngredient,codeStatus,canCopyCode,upgradeRequirements} from './core.js';

const paths={back:'m15 18-6-6 6-6',cat:'M4 9 4 3l5 3h6l5-3v12a8 8 0 0 1-16 0V9Zm4 4h.01M16 13h.01M10 17l2 1 2-1',sword:'m4 20 4-4m-3-3 6 6M9 15 20 4v5L14 15Zm-1-4 5 5',building:'M3 21h18M5 21V9l7-5 7 5v12M9 21v-6h6v6M3 9h18M9 10h.01M15 10h.01',bowl:'M3 12h18a9 9 0 0 1-18 0Zm4 8h10M8 3v5M12 2v6M16 3v5',leaf:'M20 3C8 1 1 10 6 17s16 2 14-14ZM5 20 16 9',vase:'M9 3h6M9 3v4l-4 6c-3 6 1 8 7 8s10-2 7-8l-4-6V3M7 12h10',chair:'M5 11V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v6M3 11v6h18v-6M6 17v4M18 17v4M5 11h14',book:'M3 4h7a2 2 0 0 1 2 2v15a3 3 0 0 0-3-2H3Zm18 0h-7a2 2 0 0 0-2 2v15a3 3 0 0 1 3-2h6Z',people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-2a4 4 0 0 0-3-4M16 3a4 4 0 0 1 0 8',grid:'M3 3h7v7H3ZM14 3h7v7h-7ZM3 14h7v7H3ZM14 14h7v7h-7Z',compare:'M4 4h6v16H4ZM14 4h6v16h-6Z',gift:'M3 8h18v4H3ZM5 12v9h14v-9M12 8v13M12 8S4 7 5 4s7 0 7 4Zm0 0s8-1 7-4-7 0-7 4Z',search:'m21 21-5-5M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16',home:'m3 10 9-7 9 7M5 9v12h14V9M9 21v-8h6v8',menu:'M3 6h18M3 12h18M3 18h18',check:'m5 12 4 4 10-10',external:'M14 3h7v7M10 14 21 3M21 14v7H3V3h7',close:'m6 6 12 12M18 6 6 18'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.book}"/></svg>`;
const link=(key,id='')=>`#/${key}${id?'/'+encodeURIComponent(id):''}`;
const labels={...Object.fromEntries(categories.map(c=>[c.key,c.name])),'redeem-codes':'兌換碼','skill-effects':'技能效果','stages':'攻略','artifact-sets':'古寶套裝','furniture-sets':'家具套裝','skills':'技能詳情'};
let mode=readStorage('catdynasty-mode','real');if(!dataSets[mode])mode='real';
let db=dataSets[mode];let team=readStorage(`catdynasty-team-${mode}`,[]);if(!Array.isArray(team))team=[];
let filterFocus=null;let compare=[];let menuOpen=false;let drawerHistory=[];let drawerOpener=null;
function readStorage(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function saveStorage(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}}
const get=(key,id)=>findById(db,key,id);
function badge(record){if(mode==='demo'||record.gameVersion==='mock')return '<span class="badge demo">示範資料</span>';if(record.gameVersion==='cn')return `<span class="badge reference">陸版${record.verified?'官方參考':'待補資料'}</span>`;if(record.sourceType==='official')return `<span class="badge official">${record.verified?(record.verifiedFields?.length===1&&record.verifiedFields[0]==='name'?'台版官方名稱確認':'台版官方確認'):'台版官方部分確認'}</span>`;return `<span class="badge pending">${record.sourceType==='observation'?'遊戲截圖':record.sourceType==='player'?'玩家提供':record.sourceType==='community'?'台版媒體／社群參考':'待驗證'}</span>`;}
const tag=(text,cls='')=>`<span class="tag ${cls}">${e(text)}</span>`;
const tags=values=>(values||[]).map(v=>tag(v)).join('');
const art=hero=>hero.image?`<img class="hero-art" src="${import.meta.env.BASE_URL}${e(hero.image)}" alt="${e(hero.name)}官方圖鑑" loading="lazy"/>`:`<div class="hero-placeholder">${icon('cat')}<span>圖像待補</span></div>`;
function heroCard(hero){return `<a class="hero-card" href="${link('heroes',hero.id)}"><div class="art-wrap">${art(hero)}<span class="rarity">${e(hero.rarity||'品質待補')}</span></div><div class="card-body"><div class="card-title"><h3>${e(hero.name)}</h3>${icon('external')}</div><p class="hero-meta">${e([hero.profession,hero.faction].filter(Boolean).join(' · ')||'職業與定位待核對')}</p><div class="tags">${tag(hero.attribute||'屬性待補')}</div><div class="card-footer">${badge(hero)}<span>${hero.skills.length?hero.skills.length+' 個已收錄技能':'技能待補'}</span></div></div></a>`;}
function empty(title,description,allowDemo=true){return `<div class="empty-state">${icon('book')}<h3>${e(title)}</h3><p>${e(description)}</p>${allowDemo&&mode==='real'?'<button class="button secondary" data-demo>查看功能示範</button>':''}</div>`;}
function title(name,description,extra=''){return `<div class="page-title"><div><span class="page-kicker">喵國藏書 · 小貓咪大史記</span><h1>${e(name)}</h1>${description?`<p>${e(description)}</p>`:''}</div>${extra}</div>`;}
function sourceBlock(record){const url=safeURL(record.source);return `<section class="source-block"><div>${badge(record)}${record.checkedAt?`<span>來源核對日期 ${e(record.checkedAt)}</span>`:''}</div>${record.notes?`<p>${e(record.notes)}</p>`:''}${(record.confirmations||[]).map(c=>`<p><strong>玩家已核對（${e(c.checkedAt)}）</strong>：${e(c.description)}</p>`).join('')}${url?`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">查看主要來源 ${icon('external')}</a>`:['player','observation'].includes(record.sourceType)?`<p>來源：${e(record.sourceDescription||'玩家遊戲內核對。')}</p>`:'<p>來源尚未提供。</p>'}${(record.sources||[]).filter(s=>safeURL(s.url)).map(s=>`<p><a href="${e(safeURL(s.url))}" target="_blank" rel="noopener noreferrer">${e(s.label)} ${icon('external')}</a> · ${e(s.scope)}</p>`).join('')}</section>`;}
function known(value){return value===null||value===undefined||value===''?'<span class="muted">尚未確認</span>':e(value);}
function recordLink(key,id){const record=get(key==='guides'?'stages':key,id);if(key==='ingredients')return record?e(record.name):known(null);return record?`<a class="inline-link" href="${link(key,id)}">${e(record.name||record.code)}</a>`:'<span class="muted">關聯資料待補</span>';}
function shell(){const groups=['資料庫','攻略','工具','其他'];$('#app').html(`<aside class="sidebar ${menuOpen?'open':''}" aria-label="主導覽"><a class="brand" href="#/"><span class="seal">喵</span><div><strong>喵國資料庫</strong><span>小貓咪大史記</span></div></a><nav><a class="nav-link home-link" href="#/">${icon('home')}<span>資料庫總覽</span></a>${groups.map(group=>`<div class="nav-group"><span class="nav-label">${group}</span>${categories.filter(c=>c.group===group).map(c=>`<a class="nav-link" data-nav="${c.key}" href="${link(c.key)}">${icon(c.icon)}<span>${c.name}</span></a>`).join('')}</div>`).join('')}</nav><div class="sidebar-foot"><span class="edition">台版為主 · 陸版參考</span><p>非官方攻略資料庫<br>每筆資訊保留來源與核對狀態</p></div></aside><div class="workspace"><header class="topbar"><button class="icon-button menu-button" aria-label="開啟導覽" aria-expanded="${menuOpen}" data-menu>${icon('menu')}</button><form class="global-search keyword-search" id="global-search" role="search"><label class="sr-only" for="global-query">全站搜尋</label><input type="search" id="global-query" placeholder="搜尋喵將、研究、建築、古寶…" autocomplete="off"/><button class="search-submit" type="submit" aria-label="搜尋" title="搜尋">${icon('search')}</button></form><label class="mode-control">資料模式<select id="data-mode"><option value="real"${mode==='real'?' selected':''}>已收錄資料</option><option value="demo"${mode==='demo'?' selected':''}>功能示範</option></select></label></header>${mode==='demo'?'<div class="demo-banner"><strong>功能示範模式</strong>　以下配方、加成與兌換碼均為測試範例，非遊戲資料。<button data-real>返回已收錄資料</button></div>':''}<main id="main" tabindex="-1"><div id="breadcrumbs" class="breadcrumbs"></div><div id="view"></div></main><footer class="site-footer"><span>喵國資料庫 · 非官方</span><span>台陸版本差異以遊戲內資訊為準 · 角色圖像著作權屬原權利人</span></footer></div><div class="toast" role="status" aria-live="polite" hidden></div>${drawerShell()}`);initializeDrawer();}
function drawerShell(){return `<dialog id="record-drawer" class="record-drawer" aria-labelledby="drawer-title"><header class="drawer-header"><button class="icon-button" type="button" aria-label="返回上一筆詳情" data-drawer-back hidden>${icon('back')}</button><div><span id="drawer-category" class="page-kicker"></span><h2 id="drawer-title"></h2></div><button class="icon-button drawer-close" type="button" aria-label="關閉詳情" data-drawer-close autofocus>${icon('close')}</button></header><div id="drawer-content" class="drawer-content"></div></dialog>`;}
function initializeDrawer(){const drawer=document.getElementById('record-drawer');drawer.addEventListener('close',()=>{document.documentElement.classList.remove('drawer-open');drawerHistory=[];const opener=drawerOpener;drawerOpener=null;if(opener?.isConnected)opener.focus({preventScroll:true});});drawer.addEventListener('click',event=>{if(event.target!==drawer)return;const rect=drawer.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)closeDrawer();});}
function closeDrawer(){const drawer=document.getElementById('record-drawer');if(drawer?.open)drawer.close();}
function drawerHTML(key,record){if(key==='heroes')return heroDetail(record);if(key==='stages')return guidesView(new URLSearchParams(),record.id);if(key==='redeem-codes')return codeDetail(record);return detail(key,record);}
function isSetCatalogue(target){return target?.key==='artifact-sets'&&target.kind==='list';}
function renderDrawer(){
  const target=drawerHistory.at(-1);if(!target)return;
  const catalogue=isSetCatalogue(target),record=catalogue?null:get(target.key,target.id);if(!catalogue&&!record)return;
  $('#drawer-title').text(catalogue?'古寶套裝':record.name||record.code);
  $('#drawer-category').text(catalogue?'古寶 · 套裝索引':(labels[target.key]||'資料詳情')+' · '+(record.gameVersion==='tw'?'台版':record.gameVersion==='cn'?'陸版參考':'功能示範'));
  $('#drawer-content').html(catalogue?recordList('artifact-sets',new URLSearchParams(target.params||'')):drawerHTML(target.key,record));
  $('#drawer-content > .page-title h1, #drawer-content > .page-title .page-kicker').remove();
  $('[data-drawer-back]').prop('hidden',drawerHistory.length<2);document.getElementById('drawer-content').scrollTop=target.scrollTop||0;restoreFilterFocus(document.getElementById('drawer-content'));
}
function openDrawer(target,opener){
  const drawer=document.getElementById('record-drawer');if(!drawer||(!isSetCatalogue(target)&&!get(target.key,target.id)))return;
  const alreadyOpen=drawer.open;if(!alreadyOpen){drawerHistory=[];drawerOpener=opener||document.activeElement;}
  const current=drawerHistory.at(-1);if(current)current.scrollTop=document.getElementById('drawer-content').scrollTop;
  if(isSetCatalogue(current)&&isSetCatalogue(target)){current.params=target.params;current.scrollTop=0;}
  else if(!current||current.key!==target.key||current.id!==target.id||current.kind!==target.kind)drawerHistory.push(target);
  renderDrawer();if(!alreadyOpen){drawer.showModal();document.documentElement.classList.add('drawer-open');}else document.querySelector('[data-drawer-close]').focus({preventScroll:true});
}
function ingredientText(ingredient){return `${recordLink('ingredients',ingredient.ingredientId)}${ingredient.amount===null?'':' × '+known(ingredient.amount)}`;}

function home(){const tw=db.heroes.filter(h=>h.gameVersion==='tw');return `${title('喵國藏書閣','一卷喵將，一城煙火。小貓咪大史記攻略資料庫。','<span class="edition-pill">台版為主 · 陸版參考</span>')}<div class="metrics"><a href="#/heroes"><span>喵將版本資料</span><strong>${db.heroes.length}<small>筆</small></strong></a><a href="#/buildings"><span>建築版本資料</span><strong>${db.buildings.length}<small>筆</small></strong></a><a href="#/artifacts"><span>古寶收錄</span><strong>${db.artifacts.length}<small>件</small></strong></a><a href="#/codes"><span>待實測兌換碼</span><strong>${db['redeem-codes'].filter(c=>codeStatus(c)==='unverified').length}<small>組</small></strong></a></div><section class="quick-panel"><div><span class="eyebrow">查閱藏書</span><h2>從你的喵國出發</h2></div><div class="quick-tags"><a href="#/heroes">${icon('cat')}喵將圖鑑</a><a href="#/buildings">${icon('building')}建築一覽</a><a href="#/guides">${icon('book')}新手攻略</a><a href="#/compare">${icon('compare')}勾選比較</a></div></section><div class="section-heading"><h2>喵將名錄</h2><a class="text-link" href="#/heroes">展開全部圖鑑</a></div>${heroTable((mode==='real'?tw:db.heroes).slice(0,4))}<div class="home-bottom"><section class="panel"><h2>資料庫索引</h2><div class="index-grid">${categories.filter(c=>c.group==='資料庫').map(c=>`<a href="${link(c.key)}">${icon(c.icon)}<span>${c.name}</span><small>${db[c.key].length} 筆</small></a>`).join('')}</div></section><section class="panel update-panel"><span class="eyebrow">編纂紀錄 · 2026.10.01</span><h2>每一筆資料，都有出處</h2><p>台版 ${tw.length} 筆喵將資料；陸版技能留在相應版本的喵將詳情。未知欄位等待核對。</p><a class="text-link" href="#/heroes">查看喵將圖鑑</a><p><a class="inline-link" href="#/guides">新手與聯動攻略</a> · <a class="inline-link" href="#/codes">兌換碼</a></p></section></div>`;}
function rarityLabel(hero){return hero.rarity?`${e(hero.rarity.replace(/級$/,''))}${hero.rarityType?`（${e(hero.rarityType)}）`:''}`:known(null);}
function sixArtsText(hero){return hero.sixArtsRecommendations.length?hero.sixArtsRecommendations.map(r=>`${e(r.name)}<span class="cell-note">${e(r.description)}${r.value!==null?' · '+e(r.value)+(r.unit==='percent'?'%':''):''}</span>`).join('<br>'):hero.sixArts.length?`${e(hero.sixArts.join('、'))}<span class="cell-note">效果重點；六藝名稱待補</span>`:known(null);}
function researchText(hero){return hero.researchTalents.length?hero.researchTalents.map(t=>recordLink('buildings',t.buildingId)).join('<br>'):known(null);}
function multiFilter(name,label,options,selected){return `<fieldset class="multi-filter" data-filter-group="${e(name)}"><legend class="sr-only">${e(label)}（可多選）</legend><div class="filter-group-row"><span class="filter-group-label" aria-hidden="true">${e(label)}</span><div class="filter-options"><button type="button" class="filter-pill filter-all${selected.length?'':' selected'}" data-filter-all="${e(name)}" aria-pressed="${!selected.length}">全部</button>${options.map(option=>{const [value,text]=Array.isArray(option)?option:[option,option==='unknown'?'尚未確認':option];return `<label class="filter-pill"><input class="sr-only" type="checkbox" name="${e(name)}" value="${e(value)}" ${selected.includes(value)?'checked':''}/><span>${e(text)}</span></label>`;}).join('')}</div></div></fieldset>`;}
function catalogueTable(name,headers,rows,kind='catalogue',nameColumn=0){return `<div class="data-table-scroll ${kind==='hero'?'hero-table-scroll':''}" role="region" aria-label="${e(name)}表格，可左右捲動" tabindex="0"><table class="data-table ${kind==='hero'?'hero-table':kind==='compact'?'compact-table':''}"><caption class="sr-only">${e(name)}</caption><thead><tr>${headers.map(label=>`<th scope="col">${typeof label==='object'?`<a class="hero-name-link" href="${link(label.key,label.id)}" aria-haspopup="dialog">${e(label.name)}</a>`:e(label)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map((cell,index)=>index===nameColumn?`<th scope="row">${cell}</th>`:`<td>${cell}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="table-empty">${mode==='real'?'尚未收錄可核對的資料。':'沒有符合的示範資料。'}${mode==='real'?'<button class="text-link" data-demo>查看表格示範</button>':''}</td></tr>`}</tbody></table></div>`;}
function skillTable(hero){const skills=hero.skills.map(id=>get('skills',id)).filter(Boolean);return catalogueTable(`${hero.name}技能`,['技能名稱','類型','效果','技能說明'],skills.map(s=>[`<a class="hero-name-link" href="${link('skills',s.id)}" aria-haspopup="dialog">${e(s.name)}</a>`,known(s.type),tags(s.effects.map(v=>get('skill-effects',v.type)?.name||v.type)),`${e(s.description)}<span class="cell-note">${s.cooldown===null?'冷卻與未公開數值待補':'冷卻：'+e(s.cooldown)}</span>`]));}
function heroTable(heroes){return catalogueTable('喵將圖鑑',['名稱','等級','職業','陣營','屬性','六藝推薦','研究天賦'],heroes.map(h=>[`<a class="hero-name-link" href="${link('heroes',h.id)}">${e(h.name)}</a>`,rarityLabel(h),known(h.profession),known(h.faction),known(h.attribute),sixArtsText(h),researchText(h)]),'hero');}
function heroList(params){const filters=heroFiltersFromParams(params);delete filters.version;const heroes=filterHeroes(db,filters);const rarities=[...new Set(db.heroes.map(h=>h.rarity).filter(Boolean))];const professions=[...new Set([...heroProfessions,...db.heroes.map(h=>h.profession).filter(Boolean)])];const attributes=[...new Set(db.heroes.map(h=>h.attribute).filter(Boolean))];return `${title('喵將圖鑑','查閱等級、職業、陣營、六藝推薦與研究天賦。點名稱開啟詳情抽屜。')}${catalogueFilters('heroes',params,[{name:'rarity',label:'等級',options:[...rarities.map(r=>[r,r.replace(/級$/,'')]),'unknown']},{name:'profession',label:'職業',options:[...professions,'unknown']},{name:'faction',label:'陣營',options:[...heroFactions,'unknown']},{name:'attribute',label:'屬性',options:[...attributes,'unknown']}],'搜尋喵將、研究建築或技能效果')}<div class="result-summary" role="status">找到 <strong>${heroes.length}</strong> 筆喵將資料 <span>點名稱開啟抽屜 · 表格可左右滑動</span></div>${heroTable(heroes)}`;}
function heroDetail(hero){return `${title(hero.name,hero.description,`<button class="button" data-team-add="${e(hero.id)}">加入我的隊伍</button>`)}<div class="hero-detail-layout"><div class="portrait-panel">${art(hero)}${safeURL(hero.source)?`<a href="${hero.image?import.meta.env.BASE_URL+e(hero.image):e(safeURL(hero.source))}" target="_blank" rel="noopener noreferrer">${hero.image?'查看官方完整圖鑑':'查看介紹來源'} ${icon('external')}</a>`:''}</div><section class="panel"><div class="detail-summary">${badge(hero)}</div><dl class="facts">${[['等級',rarityLabel(hero)],['職業',known(hero.profession)],['陣營',known(hero.faction)],['屬性',known(hero.attribute)],['六藝推薦',sixArtsText(hero)],['研究天賦',researchText(hero)]].map(([label,value])=>`<div><dt>${label}</dt><dd>${value}</dd></div>`).join('')}</dl>${hero.acquisition?.length?`<h2 class="spacious">取得方式</h2><ul>${hero.acquisition.map(v=>`<li>${e(v)}</li>`).join('')}</ul>`:''}</section></div><section class="panel spacious"><h2>技能詳情</h2>${hero.skills.length?skillTable(hero):'<p class="muted">尚未取得可核對的技能內容；未公開數值保留待補。</p>'}</section><div class="two-columns"><section class="panel"><h2>研究天賦與建設能力</h2>${hero.researchTalents.map(t=>`<div class="relation-row"><div>${recordLink('buildings',t.buildingId)}<p>${e(t.description)}</p></div></div>`).join('')}${hero.buildingBonuses.map(b=>`<div class="relation-row"><div>${recordLink('buildings',b.buildingId)}<p>經營技能 · ${e(b.description)}</p></div><strong>${b.value===null?'數值待補':e(b.value)+'%'}</strong></div>`).join('')}${!hero.researchTalents.length&&!hero.buildingBonuses.length?'<p class="muted">研究天賦與建築加成尚未確認。</p>':''}</section><section class="panel"><h2>推薦搭配</h2>${db.teams.filter(t=>t.heroIds.includes(hero.id)).map(t=>`<div class="relation-row"><div>${recordLink('teams',t.id)}<p>${t.heroIds.map(id=>recordLink('heroes',id)).join(' · ')}</p></div></div>`).join('')||'<p class="muted">尚未收錄推薦隊伍。</p>'}</section></div>${sourceBlock(hero)}`;}
function recordCard(key,record){
  const category=categories.find(c=>c.key===key);
  return `<a class="record-card" href="${link(key,record.id)}"><div class="record-icon">${icon(category?.icon||'book')}</div><div><div class="card-title"><h3>${e(record.name||record.code)}</h3>${icon('external')}</div><p>${e(record.description||'詳細資料待補。')}</p><div class="tags">${tags(record.effectTags||[record.type,record.rarity].filter(Boolean))}</div><div class="card-footer">${badge(record)}</div></div></a>`;
}
const artifactQualityOrder=['御品','珍品','良品'];
const artifactQualityRank=rarity=>artifactQualityOrder.includes(rarity)?artifactQualityOrder.indexOf(rarity):artifactQualityOrder.length;
const compareArtifactQuality=(a,b)=>artifactQualityRank(a.rarity)-artifactQualityRank(b.rarity);
const recipeCuisines=['川','粵','湘','浙','特'];
function keywordSearch(section,params,placeholder='輸入關鍵字'){
  const queryName=section==='search'?'q':'query',id=`${section}-query${document.getElementById('record-drawer')?.open?'-drawer':''}`;
  return `<form class="global-search keyword-search generic-filter" data-section="${e(section)}" role="search" aria-label="搜尋${e(labels[section]||'資料')}"><label class="sr-only" for="${e(id)}">搜尋關鍵字</label><input id="${e(id)}" type="search" name="${queryName}" value="${e(params.get(queryName)||'')}" placeholder="${e(placeholder)}"/>${[...params].filter(([name])=>name!==queryName&&name!=='version').map(([name,value])=>`<input type="hidden" name="${e(name)}" value="${e(value)}"/>`).join('')}<button class="search-submit" type="submit" aria-label="搜尋" title="搜尋">${icon('search')}</button></form>`;
}
function catalogueFilters(section,params,groups,placeholder='輸入關鍵字'){
  const queryName=section==='search'?'q':'query';
  return `<div class="catalogue-controls">${keywordSearch(section,params,placeholder)}${groups.length?`<form class="filter-bar multi-filter-form generic-filter" data-section="${e(section)}" ${section==='heroes'?'id="hero-filters"':''}><input type="hidden" name="${queryName}" value="${e(params.get(queryName)||'')}"/>${groups.map(({name,label,options})=>multiFilter(name,label,options,params.getAll(name))).join('')}</form>`:''}</div>`;
}
function recordControls(key,params,records){
  const types=[...new Set(records.map(r=>r.type).filter(Boolean))],effects=[...new Set(records.flatMap(r=>[...(r.effectTags||[]),...(r.setIds||[]).flatMap(id=>get('artifact-sets',id)?.effectTags||[])]))];
  const groups=[];
  if(key==='recipes')groups.push({name:'cuisine',label:'菜系',options:recipeCuisines});
  if(types.length)groups.push({name:'type',label:'類型',options:types});
  if(effects.length)groups.push({name:'effect',label:'效果',options:effects});
  if(key==='artifacts'&&db['artifact-sets'].length)groups.push({name:'set',label:'套裝',options:db['artifact-sets'].map(s=>[s.id,s.name])});
  return catalogueFilters(key,params,groups,key==='recipes'?'搜尋食譜或食材':'搜尋名稱或關聯');
}
function restoreFilterFocus(root){
  if(!filterFocus)return;
  const {name,value,section,scrollLeft=0}=filterFocus;
  const form=[...root.querySelectorAll('.multi-filter-form')].find(form=>form.dataset.section===section);
  const controls=form?[...form.querySelectorAll(value===null?'[data-filter-all]':'input[type=checkbox]')]:[];
  const target=controls.find(control=>value===null?control.dataset.filterAll===name:control.name===name&&control.value===value);
  if(target){target.closest('.filter-options').scrollLeft=scrollLeft;target.focus({preventScroll:true});}
  filterFocus=null;
}
function localKeywordSearch(id,placeholder){return `<form class="global-search keyword-search local-keyword-search" role="search" aria-label="${e(placeholder)}"><label class="sr-only" for="${e(id)}">${e(placeholder)}</label><input id="${e(id)}" type="search" placeholder="${e(placeholder)}"/><button class="search-submit" type="submit" aria-label="搜尋" title="搜尋">${icon('search')}</button></form>`;}
function recordList(key,params){params=new URLSearchParams(params);params.delete('version');const records=db[key]||[],results=filterRecords(db,key,params);const descriptions={buildings:'建築功能、研究天賦與升級資料。',recipes:'查閱菜系、配方與菜譜等級；點食譜名稱開啟詳情抽屜。',artifacts:'依稀有度排列；點名稱查看大圖、被動效果與截圖進度。','artifact-sets':'套裝成員、套裝效果與 9 星／18 星效果。',furniture:'家具類型、效果、擺放位置與套裝。',teams:'有來源的推薦搭配，可載入隊伍編輯器。','furniture-sets':'套裝成員與件數效果。'};const name=r=>`<a class="hero-name-link" href="${link(key,r.id)}">${e(r.name)}</a>`;const maps={buildings:{headers:['名稱','類型','功能'],row:r=>[name(r),known(r.type),e(r.description)]},recipes:{headers:['菜系','食譜名稱','配方','菜譜等級'],nameColumn:1,row:r=>[known(r.cuisine),name(r),r.ingredients.length?r.ingredients.map(ingredientText).join(' ＋ '):known(null),typeof r.recipeLevel==='number'?`${r.recipeLevel} 級`:known(r.recipeLevel)]},artifacts:{headers:['稀有度','名稱','大小','被動效果','生效數量','套裝'],nameColumn:1,row:r=>[known(r.rarity),artifactNameLink(r),known(r.size),known(r.passiveEffect),Number.isInteger(r.effectiveLimit)?r.effectiveLimit+' 次':known(null),artifactSetLinks(r)]},'artifact-sets':{headers:['套裝名稱','成員','套裝效果','9 星套裝','18 星套裝'],row:r=>[name(r),r.artifactIds.map(id=>recordLink('artifacts',id)).join('、'),...r.bonuses.map(b=>e(b.description))]},teams:{headers:['隊伍名稱','推薦喵將','隊伍說明','操作'],row:r=>[name(r),r.heroIds.map(id=>recordLink('heroes',id)).join('、'),e(r.description),`<button type="button" class="button secondary" data-load-team="${e(r.id)}">載入隊伍</button>`]},furniture:{headers:['名稱','類型','品質','屬性／效果','擺放位置','套裝','取得方式'],row:r=>[name(r),known(r.type),known(r.rarity),tags(r.effectTags)||known(null),r.placement.length?e(r.placement.join('、')):known(null),r.setId?recordLink('furniture-sets',r.setId):known(null),r.acquisition.length?e(r.acquisition.join('、')):known(null)]}};if(key==='artifacts')results.sort(compareArtifactQuality);if(key==='recipes'){const rank=cuisine=>recipeCuisines.includes(cuisine)?recipeCuisines.indexOf(cuisine):recipeCuisines.length;results.sort((a,b)=>rank(a.cuisine)-rank(b.cuisine));}const config=maps[key];return `${title(labels[key]||key,descriptions[key],key==='furniture'?'<a class="button secondary" href="#/furniture-sets">家具套裝</a>':key==='artifacts'?'<a class="button secondary" href="#/artifact-sets" aria-haspopup="dialog" aria-controls="record-drawer">古寶套裝</a>':'')}${recordControls(key,params,records)}<div class="result-summary" role="status">找到 <strong>${results.length}</strong> 筆資料</div>${config?catalogueTable(labels[key],config.headers,results.map(config.row),'catalogue',config.nameColumn||0):results.length?`<div class="record-grid">${results.map(r=>recordCard(key,r)).join('')}</div>`:empty('尚無可核對的資料','取得可靠遊戲資料後補入。')}`;}
function levelTable(levels){return levels.length?`<div class="table-scroll"><table><thead><tr><th>等級</th><th>主城條件</th><th>資源</th><th>時間</th><th>資料狀態</th></tr></thead><tbody>${levels.sort((a,b)=>a.level-b.level).map(l=>`<tr><td>Lv.${l.level}</td><td>${known(l.requirements.cityLevel)}</td><td>${l.requirements.resources.length?l.requirements.resources.map(r=>`${recordLink('ingredients',r.id)} × ${r.amount}`).join('<br>'):'無資源條件記錄'}</td><td>${l.buildTime===null?known(null):`${e(l.buildTime)} 秒`}</td><td>${badge(l)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">各級解鎖條件、材料與建造時間尚未確認。</p>';}
function buildingDetail(record){
  const heroes=heroesForBuilding(db,record.id);const recipes=db.recipes.filter(r=>r.buildingId===record.id);
  return `${title(record.name,record.description)}<div class="two-columns"><section class="panel"><h2>建築資訊</h2><dl class="facts"><div><dt>類型</dt><dd>${known(record.type)}</dd></div><div><dt>主城解鎖等級</dt><dd>${known(record.unlock.cityLevel)}</dd></div><div><dt>其他解鎖條件</dt><dd>${known(record.unlock.condition)}</dd></div><div><dt>已知升級資料</dt><dd>${record.levels.length} 個等級</dd></div></dl></section><section class="panel"><h2>可加速喵將</h2>${heroes.length?heroes.map(h=>{const b=h.buildingBonuses.find(x=>x.buildingId===record.id);return `<div class="relation-row"><div>${recordLink('heroes',h.id)}<p>${e(b.description)}</p></div><strong>${b.value===null?'數值待補':e(b.value)+'%'}</strong></div>`;}).join(''):'<p class="muted">加速喵將尚未確認。</p>'}</section></div>${db.heroes.some(h=>h.researchTalents.some(t=>t.buildingId===record.id))?`<section class="panel"><h2>研究天賦喵將</h2>${db.heroes.filter(h=>h.researchTalents.some(t=>t.buildingId===record.id)).map(h=>`<p>${recordLink('heroes',h.id)}</p>`).join('')}</section>`:''}${record.rewardConditions?.length?`<section class="panel"><h2>等級領取獎勵</h2>${record.rewardConditions.map(r=>`<div class="relation-row"><strong>Lv.${r.level}</strong><div>${recordLink('heroes',r.heroId)}<p>${e(r.description)}</p></div></div>`).join('')}</section>`:''}<section class="panel"><div class="section-heading"><h2>升級條件</h2><a class="text-link" href="#/requirements?building=${e(record.id)}">計算升級需求</a></div>${levelTable(db['building-levels'].filter(l=>l.buildingId===record.id))}</section><div class="two-columns"><section class="panel"><h2>生產內容</h2>${record.production.length?record.production.map(id=>`<div class="relation-row">${recordLink('ingredients',id)}</div>`).join(''):'<p class="muted">生產內容尚未確認。</p>'}</section><section class="panel"><h2>相關食譜</h2>${recipes.length?recipes.map(r=>`<div class="relation-row">${recordLink('recipes',r.id)}</div>`).join(''):'<p class="muted">尚未收錄相關食譜。</p>'}</section></div>${sourceBlock(record)}`;
}
function recipeDetail(record){return `${title(record.name,record.description)}<div class="two-columns"><section class="panel"><h2>配方材料</h2>${record.ingredients.length?record.ingredients.map(i=>`<div class="relation-row">${recordLink('ingredients',i.ingredientId)}<strong>${i.amount===null?'<span class="muted">用量待補</span>':'× '+known(i.amount)}</strong></div>`).join(''):'<p class="muted">配方材料尚未確認。</p>'}</section><section class="panel"><h2>菜譜與製作條件</h2><dl class="facts"><div><dt>菜系</dt><dd>${known(record.cuisine)}</dd></div><div><dt>菜譜等級</dt><dd>${typeof record.recipeLevel==='number'?`${record.recipeLevel} 級`:known(record.recipeLevel)}</dd></div><div><dt>製作建築</dt><dd>${record.buildingId?recordLink('buildings',record.buildingId):known(null)}</dd></div><div><dt>產出數量</dt><dd>${known(record.outputAmount)}</dd></div><div><dt>製作時間</dt><dd>${record.craftTime===null?known(null):e(record.craftTime)+' 秒'}</dd></div><div><dt>解鎖條件</dt><dd>${known(record.unlock)}</dd></div></dl></section></div>${sourceBlock(record)}`;}
function ingredientDetail(record){const recipes=recipesForIngredient(db,record.id);return `${title(record.name,record.description)}<div class="two-columns"><section class="panel"><h2>可以製作的食譜</h2>${recipes.length?recipes.map(r=>`<div class="relation-row">${recordLink('recipes',r.id)}<span>需 ${known(r.ingredients.find(i=>i.ingredientId===record.id).amount)} 份</span></div>`).join(''):'<p class="muted">尚未收錄使用此食材的食譜。</p>'}</section><section class="panel"><h2>取得來源</h2>${record.obtainedFrom.length?record.obtainedFrom.map(id=>`<div class="relation-row">${recordLink('buildings',id)}</div>`).join(''):'<p class="muted">取得方式尚未確認。</p>'}</section></div>${sourceBlock(record)}`;}
const statLabels={health:'生命',crit_up:'暴擊提升',speed_up:'速度提升',attack_up:'攻擊提升',damage_reduction:'減傷'};
function statsTable(effects){return effects.length?effects.map(effect=>`<div class="relation-row"><span>${e(get('skill-effects',effect.type)?.name||statLabels[effect.type]||(effect.type==='production_efficiency'?'生產效率':effect.type))}</span><strong>${effect.value===null?'數值待補':e(effect.value)+(effect.unit==='percent'?'%':'')}</strong>${effect.condition?`<p>${e(effect.condition)}${effect.buildingId?' · '+recordLink('buildings',effect.buildingId):''}</p>`:''}</div>`).join(''):'<p class="muted">屬性效果尚未確認。</p>';}
function artifactNameLink(record){return `<a class="hero-name-link artifact-name-link" href="${link('artifacts',record.id)}" aria-haspopup="dialog">${record.image?`<img class="artifact-thumbnail" src="${import.meta.env.BASE_URL}${e(record.image)}" alt="" loading="lazy" width="48" height="48"/>`:`<span class="artifact-thumbnail artifact-image-pending" aria-hidden="true">${icon('vase')}</span>`}<span>${e(record.name)}</span></a>`;}
function artifactExtras(record){const levels=db['artifact-levels'].filter(l=>l.artifactId===record.id);return `${record.effects.length?`<section class="panel"><h2>基礎效果</h2>${statsTable(record.effects)}</section>`:''}<div class="two-columns"><section class="panel"><h2>適用喵將與隊伍</h2>${[...record.heroIds.map(id=>recordLink('heroes',id)),...record.teamIds.map(id=>recordLink('teams',id))].map(x=>`<div class="relation-row">${x}</div>`).join('')||'<p class="muted">尚未收錄有來源的搭配。</p>'}</section><section class="panel"><h2>升級與強化</h2>${levels.length?levels.map(l=>`<h3>Lv.${l.level}</h3>${statsTable(l.effects)}<p class="muted">${l.requirements.length?l.requirements.map(r=>e(r.id)+' × '+r.amount).join('、'):'強化材料尚未確認。'}</p>`).join(''):'<p class="muted">強化效果與材料尚未確認。</p>'}</section></div>`;}
function artifactDetail(record){
 const sets=(record.setIds||[]).map(id=>get('artifact-sets',id)).filter(Boolean),progress=record.screenshotProgress;
 return `${title(record.name,record.description)}<section class="panel artifact-overview">${record.image?`<div class="artifact-illustration"><img src="${import.meta.env.BASE_URL}${e(record.image)}" alt="${e(record.name)}古寶去背圖" width="1024" height="1024"/></div>`:'<div class="artifact-illustration muted">圖像待補</div>'}<div class="artifact-overview-body"><dl class="artifact-facts"><div><dt>稀有度</dt><dd>${known(record.rarity)}</dd></div><div><dt>大小</dt><dd>${known(record.size)}</dd></div><div><dt>生效上限</dt><dd>${Number.isInteger(record.effectiveLimit)?record.effectiveLimit+' 次':known(null)}</dd></div></dl><h2>被動效果</h2><p>${known(record.passiveEffect)}</p><div class="tags spacious">${tags(record.effectTags)}</div></div></section>${progress?`<section class="panel artifact-progress"><h2>截圖當下進度</h2><p class="muted">以下為截圖帳號當時的狀態。</p><p class="muted">${e(record.sourceDescription)}</p><dl class="artifact-facts"><div><dt>生效數量</dt><dd>${progress.effectiveCount}／${record.effectiveLimit} 次</dd></div><div><dt>放置數量</dt><dd>${progress.placedCount}／${progress.placementLimit}</dd></div></dl><p>累計效果：${e(progress.totalEffect)}</p></section>`:''}${sets.length?sets.map(s=>`<section class="panel"><h2>${recordLink('artifact-sets',s.id)}</h2><p>${s.artifactIds.map(id=>recordLink('artifacts',id)).join('、')}</p>${artifactSetBonuses(s)}</section>`).join(''):'<section class="panel"><h2>套裝</h2><p class="muted">套裝關聯尚未確認。</p></section>'}<section class="panel"><h2>取得方式</h2>${record.acquisition.length?`<ul>${record.acquisition.map(x=>`<li>${e(x)}</li>`).join('')}</ul>`:'<p class="muted">取得方式尚未確認。</p>'}</section>${artifactExtras(record)}${sourceBlock(record)}`;
}
function furnitureDetail(record){const set=get('furniture-sets',record.setId);return `${title(record.name,record.description)}<div class="two-columns"><section class="panel"><h2>家具資訊</h2><dl class="facts"><div><dt>類型</dt><dd>${known(record.type)}</dd></div><div><dt>品質</dt><dd>${known(record.rarity)}</dd></div><div><dt>擺放位置</dt><dd>${record.placement.length?e(record.placement.join('、')):known(null)}</dd></div><div><dt>套裝</dt><dd>${set?recordLink('furniture-sets',set.id):known(null)}</dd></div></dl><div class="tags spacious">${tags(record.effectTags)}</div>${statsTable(record.effects)}</section><section class="panel"><h2>取得方式與相關空間</h2><p>${record.acquisition.length?e(record.acquisition.join('、')):'取得方式尚未確認。'}</p><div class="tags spacious">${tags(record.spaceTags)}</div>${record.buildingIds.map(id=>`<div class="relation-row">${recordLink('buildings',id)}</div>`).join('')}</section></div>${set?`<section class="panel"><h2>${recordLink('furniture-sets',set.id)}</h2><p>${set.furnitureIds.map(id=>recordLink('furniture',id)).join(' · ')}</p>${set.bonuses.map(b=>`<div class="relation-row"><strong>${b.pieces} 件套</strong><p>${e(b.description)}</p>${tags(b.effectTags)}</div>`).join('')}</section>`:''}${sourceBlock(record)}`;}
function setDetail(record){return `${title(record.name,'集齊套裝件數後，查看對應效果。')}<section class="panel"><h2>套裝成員</h2><div class="record-grid">${record.furnitureIds.map(id=>recordCard('furniture',get('furniture',id))).join('')}</div></section><section class="panel"><h2>套裝效果</h2>${record.bonuses.map(b=>`<h3>${b.pieces} 件套</h3><p>${e(b.description)}</p>${statsTable(b.effects)}`).join('')}</section>${sourceBlock(record)}`;}
function skillDetail(record){const heroes=db.heroes.filter(h=>h.skills.includes(record.id));return `${title(record.name,record.description)}<section class="panel"><dl class="facts"><div><dt>技能類型</dt><dd>${known(record.type)}</dd></div><div><dt>作用目標</dt><dd>${known(record.target)}</dd></div><div><dt>冷卻</dt><dd>${known(record.cooldown)}</dd></div></dl></section><section class="panel"><h2>技能效果</h2><div class="tags spacious">${record.effects.map(v=>`<a href="#/heroes?effect=${e(v.type)}">${tag(get('skill-effects',v.type)?.name||v.type)}</a>`).join('')}</div><p class="muted">未公開的倍率、機率與持續時間保留未知；技能升級差异請參閱原圖鑑。</p></section><section class="panel"><h2>擁有此技能的喵將</h2><div class="hero-grid">${heroes.map(heroCard).join('')}</div></section>${sourceBlock(record)}`;}
function effectDetail(record){const heroes=db.heroes.filter(h=>effectIdsForHero(db,h).includes(record.id));const skills=db.skills.filter(s=>s.effects.some(v=>v.type===record.id));return `${title(record.name,'依技能效果反查喵將與技能。')}<section class="panel"><h2>擁有此效果的喵將</h2><div class="hero-grid">${heroes.map(heroCard).join('')||'<p class="muted">尚未收錄。</p>'}</div></section><section class="panel"><h2>相關技能</h2><div class="record-grid">${skills.map(s=>recordCard('skills',s)).join('')}</div></section>`;}
function teamDetail(record){return `${title(record.name,record.description,`<button class="button" data-load-team="${e(record.id)}">載入隊伍編輯器</button>`)}<div class="hero-grid team-grid">${record.heroIds.map(id=>heroCard(get('heroes',id))).join('')}</div><section class="panel"><h2>已知隊伍效果</h2><div class="tags">${effectsForTeam(db,record.heroIds).map(id=>tag(get('skill-effects',id)?.name||id)).join('')||'<p class="muted">技能資料尚未完整，無法彙總。</p>'}</div><p class="muted spacious">效果彙總僅包含已收錄技能，不代表完整隊伍能力。</p></section>${sourceBlock(record)}`;}
function searchView(params){
  const query=params.get('q')||'',categories=params.getAll('category').filter(Boolean);
  const all=searchDatabase(db,query).filter(r=>!['skills','skill-effects','ingredients'].includes(r.key));
  const results=all.filter(r=>!categories.length||categories.includes(r.key));
  const foundKeys=[...new Set(all.map(r=>r.key))];
  return `${title('全站搜尋',query?`「${query}」的名稱、技能與關聯查詢結果。`:'輸入關鍵字搜尋整個資料庫。')}${catalogueFilters('search',params,foundKeys.length?[{name:'category',label:'分類',options:foundKeys.map(k=>[k,labels[k]||k])}]:[],'例如：治療、太醫院、暴擊')}<div class="result-summary" role="status">找到 <strong>${results.length}</strong> 筆資料</div><div class="search-results">${results.length?results.map(({key,record,related})=>`<a class="search-result" href="${link(key==='redeem-codes'?'codes':key==='stages'?'guides':key,record.id)}"><div><span class="eyebrow">${e(labels[key]||key)}${related?' · 關聯符合':''}</span><h3>${e(record.name||record.code)}</h3><p>${e(record.description||record.notes||'查看詳細資料')}</p></div>${badge(record)}</a>`).join(''):empty(query?'沒有符合的資料':'開始查詢','可搜尋角色名、技能效果、建築、食譜、古寶與家具。',false)}</div>`;
}
function artifactSetLinks(record){return (record.setIds||[]).length?record.setIds.map(id=>recordLink('artifact-sets',id)).join('、'):known(null);}
function artifactSetBonuses(set){return catalogueTable(set.name+'套裝效果',['條件','效果'],set.bonuses.map(b=>[e(b.label),e(b.description)]),'compact');}
function artifactSetDetail(record){return `${title(record.name,'套裝成員與三階效果，依玩家提供的遊戲截圖記錄。')}<section class="panel"><h2>套裝成員</h2>${catalogueTable(record.name+'成員',['稀有度','古寶名稱'],record.artifactIds.map(id=>get('artifacts',id)).filter(Boolean).sort(compareArtifactQuality).map(artifact=>[known(artifact.rarity),artifactNameLink(artifact)]),'compact',1)}</section><section class="panel"><h2>套裝效果</h2>${artifactSetBonuses(record)}</section>${sourceBlock(record)}`;}
function codeCopyButton(code){return `<button class="button secondary" type="button" data-copy-code="${e(code.id)}" ${!canCopyCode(code,{demo:mode==='demo'})?'disabled':''}>${mode==='demo'?'示範碼不提供複製':codeStatus(code)==='unverified'?'複製待驗證碼':'複製兌換碼'}</button>`;}
const codeStatusNames={active:'已核實有效',expired:'已過來源期限／已失效',unverified:'有效性待驗證',upcoming:'尚未開始'};
function codeDetail(record){return `${title(record.code,'兌換碼詳情與來源紀錄。')}<section class="panel"><dl class="facts"><div><dt>狀態</dt><dd>${e(codeStatusNames[codeStatus(record)])}</dd></div><div><dt>獎勵</dt><dd>${e(record.rewards.join('、')||'獎勵尚未確認')}</dd></div><div><dt>來源標示到期日</dt><dd>${record.endDate?e(record.endDate):'未提供'}</dd></div><div><dt>遊戲實測日期</dt><dd>${record.lastTestedAt?e(record.lastTestedAt):'尚未實測'}</dd></div></dl><div class="spacious">${codeCopyButton(record)}</div></section>${sourceBlock(record)}`;}
function codesView(params,id){if(id){const record=get('redeem-codes',id);return record?codeDetail(record):empty('找不到兌換碼','請返回兌換碼表格。',false);}const codes=filterRecords(db,'redeem-codes',params);const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'});const due=codes.filter(c=>c.endDate===today);return `${title('兌換碼','點兌換碼開啟詳情抽屜；待驗證碼可複製至遊戲內試用。')}<p><a class="inline-link" href="#/guides/guide_codes_tw">兌換方式與核對說明</a> · 已核實有效 ${db['redeem-codes'].filter(c=>codeStatus(c)==='active').length} 組 · 待驗證 ${db['redeem-codes'].filter(c=>codeStatus(c)==='unverified').length} 組</p>${due.length?`<p class="missing-note">${due.length} 組代碼的來源到期日為今天（${e(today)}）；截止時刻與有效性尚未實測。</p>`:''}${catalogueFilters('codes',params,[{name:'status',label:'狀態',options:[['active','有效'],['unverified','待驗證'],['expired','已失效'],['upcoming','尚未開始']]}],'搜尋兌換碼或獎勵')}${catalogueTable('兌換碼',['兌換碼','獎勵','狀態','來源到期日','操作'],codes.map(c=>[`<a class="hero-name-link" href="${link('codes',c.id)}">${e(c.code)}</a>`,e(c.rewards.join('、')||'獎勵尚未確認'),e(codeStatusNames[codeStatus(c)]),c.endDate?e(c.endDate):'未提供',codeCopyButton(c)]))}`;}

function guidesView(params,id){const records=id?db.stages.filter(s=>s.id===id):filterRecords(db,'stages',params);return `${title('關卡與系統攻略','新手發展、養成、布置與活動資訊，附來源及核對狀態。')}${id?'':catalogueFilters('guides',params,[{name:'type',label:'類型',options:['關卡','Boss','系統','活動']}],'搜尋關卡、Boss 或系統攻略')}${records.length?records.map(r=>`<section class="panel"><h2>${recordLink('guides',r.id)}</h2><div class="tags spacious">${tag(r.type)}${badge(r)}</div><p>${e(r.description)}</p>${r.endAt?`<p>來源標示截止：${e(r.endAt.replace('T',' ').replace('+08:00','（台灣時間）'))}${r.endDate<new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'})?' · 已過來源期限':''}</p>`:''}${(r.sections||[]).map(s=>`<h3>${e(s.heading)}</h3><ul>${s.items.map(item=>`<li>${e(item)}</li>`).join('')}</ul>`).join('')}${[['heroes',r.heroIds],['teams',r.teamIds],['buildings',r.buildingIds||[]],['artifacts',r.artifactIds||[]]].filter(([,ids])=>ids.length).map(([key,ids])=>`<p class="spacious">${ids.map(id=>recordLink(key,id)).join(' · ')}</p>`).join('')}${sourceBlock(r)}</section>`).join(''):empty('攻略資料整理中','關卡與 Boss 攻略會在取得可靠遊戲資料後加入。')}`;}
function teamBuilder(){team=team.filter(id=>get('heroes',id)).slice(0,5);const effects=effectsForTeam(db,team);return `${title('隊伍編輯器','選擇最多五位喵將，查看已知技能效果。','<button class="button secondary" data-clear-team>清空隊伍</button>')}<section class="panel"><div class="section-heading"><h2>我的隊伍</h2><span class="muted">${team.length} / 5 位 · 儲存於這台裝置</span></div><div class="team-slots">${Array.from({length:5},(_,i)=>{const h=get('heroes',team[i]);return h?`<div class="team-slot filled"><div class="slot-art">${art(h)}</div><h3>${e(h.name)}</h3>${tags([h.profession,h.faction].filter(Boolean))}<button class="text-link" data-team-remove="${e(h.id)}">移除</button></div>`:`<div class="team-slot"><span class="slot-number">0${i+1}</span>${icon('cat')}<p>選擇喵將</p></div>`;}).join('')}</div><div class="team-effect-row"><strong>隊伍效果</strong><div class="tags">${effects.map(id=>tag(get('skill-effects',id)?.name||id)).join('')||'<span class="muted">加入有技能資料的喵將後顯示。</span>'}</div></div><p class="muted">僅彙總已知技能；不推測強度，也不把陸版效果視為台版確認。</p></section><section class="panel"><div class="section-heading"><h2>選擇喵將</h2></div>${localKeywordSearch('team-query','搜尋可選喵將')}<div class="hero-picker">${db.heroes.map(h=>`<div class="picker-row" data-name="${e(h.name)}"><div><strong>${e(h.name)}</strong><p>${e([h.profession,h.faction].filter(Boolean).join(' · ')||'職業與陣營待補')}</p></div>${badge(h)}<button class="button secondary" data-picker-add="${e(h.id)}" ${team.includes(h.id)||team.length>=5?'disabled':''}>${team.includes(h.id)?'已加入':'加入'}</button></div>`).join('')}</div></section>`;}
function compareView(){const heroes=compare.map(id=>get('heroes',id)).filter(Boolean);return `${title('喵將比較','直接勾選最多三位喵將，台陸版本分開標示。')}${localKeywordSearch('compare-query','搜尋可比較喵將')}<form id="compare-form" class="panel"><div class="section-heading"><h2>選擇喵將</h2><span id="compare-count" role="status">已選 ${heroes.length} / 3 位</span></div><div class="compare-picker">${db.heroes.map(h=>`<label class="compare-option" data-compare-name="${e(h.name)}"><input type="checkbox" name="heroes" value="${e(h.id)}" ${compare.includes(h.id)?'checked':''}/><span><strong>${e(h.name)}</strong><small>${h.gameVersion==='tw'?'台版':h.gameVersion==='cn'?'陸版參考':'功能示範'} · ${e(h.profession||'職業待補')} · ${e(h.faction||'陣營待補')}</small></span></label>`).join('')}</div><div class="filter-actions"><button class="button" type="submit">比較所選喵將</button><button class="button secondary" type="button" data-clear-compare>清除選擇</button></div></form>${heroes.length?catalogueTable('喵將比較',['比較項目',...heroes.map(h=>({name:h.name,key:'heroes',id:h.id}))],[['等級',...heroes.map(rarityLabel)],['職業',...heroes.map(h=>known(h.profession))],['陣營',...heroes.map(h=>known(h.faction))],['屬性',...heroes.map(h=>known(h.attribute))],['六藝推薦',...heroes.map(sixArtsText)],['研究天賦',...heroes.map(researchText)],['技能詳情',...heroes.map(h=>`<a class="inline-link" href="${link('heroes',h.id)}">查看${e(h.name)}詳情</a>`)]],'compare'):empty('勾選想比較的喵將','桌面與手機都能直接勾選多位。',false)}`;}
function requirementsView(params){const building=params.get('building')||db.buildings[0]?.id;return `${title('建築需求','累加已收錄等級的材料；缺少資料時顯示缺漏等級。')}<form id="requirements-form" class="filter-bar"><label class="filter-field query-field">建築<select name="building" required>${db.buildings.map(b=>`<option value="${e(b.id)}" ${building===b.id?'selected':''}>${e(b.name)}（${b.gameVersion==='tw'?'台版':b.gameVersion==='cn'?'陸版參考':'示範'}）</option>`).join('')}</select></label><label class="filter-field">目前等級<input name="from" type="number" min="0" max="999" value="0" required/></label><label class="filter-field">目標等級<input name="to" type="number" min="1" max="1000" value="2" required/></label><button class="button" ${!db.buildings.length?'disabled':''}>計算需求</button></form><div id="requirements-result">${empty('選擇建築與等級','沒有資料的級別會列為待補，不會計算成零。',false)}</div>`;}
function detail(key,record){const views={buildings:buildingDetail,recipes:recipeDetail,ingredients:ingredientDetail,artifacts:artifactDetail,'artifact-sets':artifactSetDetail,furniture:furnitureDetail,'furniture-sets':setDetail,skills:skillDetail,'skill-effects':effectDetail,teams:teamDetail};return views[key]?.(record)||empty('找不到詳細頁','請返回資料庫索引。',false);}
function render(){
  closeDrawer();db=dataSets[mode];const url=new URL(location.hash.slice(1)||'/', 'https://wiki.local');const [section='',encodedId='']=url.pathname.split('/').filter(Boolean);let id;try{id=decodeURIComponent(encodedId);}catch{id=encodedId;}
  if(['skills','skill-effects','ingredients'].includes(section)){const owner=section==='skills'&&id?db.heroes.find(h=>h.skills.includes(id)):null;location.hash=owner?link('heroes',owner.id):section==='ingredients'?'#/recipes':section==='skill-effects'&&id?'#/heroes?effect='+encodeURIComponent(id):'#/heroes';return;}
  if(section==='artifact-sets'){const target=detailTargetFromHash(db,location.hash);history.replaceState(history.state,'','#/artifacts');render();if(target)openDrawer(target);return;}
  const current=categories.find(c=>c.key===section);$('.nav-link').removeClass('active');$('.nav-link').filter(function(){return section?this.dataset.nav===(section==='artifact-sets'?'artifacts':section):this.classList.contains('home-link');}).addClass('active');
  $('#breadcrumbs').html(`<a href="#/">總覽</a>${section?`<span>/</span><a href="${link(section)}">${e(current?.name||labels[section]||'搜尋')}</a>`:''}${id?'<span>/</span><span>詳細資料</span>':''}`);
  let html;
  if(!section)html=home();
  else if(section==='heroes')html=id?(get('heroes',id)?heroDetail(get('heroes',id)):empty('找不到喵將','此連結可能不屬於目前資料模式。')):heroList(url.searchParams);
  else if(section==='search')html=searchView(url.searchParams);
  else if(section==='codes')html=codesView(url.searchParams,id);
  else if(section==='guides')html=guidesView(url.searchParams,id);
  else if(section==='team-builder')html=teamBuilder();
  else if(section==='compare')html=compareView();
  else if(section==='requirements')html=requirementsView(url.searchParams);
  else if(db[section])html=id?(get(section,id)?detail(section,get(section,id)):empty('找不到資料','此連結可能不屬於目前資料模式。')):recordList(section,url.searchParams);
  else html=empty('找不到頁面','請從左側導覽選擇資料分類。',false);
  $('#view').html(html);document.title=`${current?.name||labels[section]||'喵國資料庫'}｜小貓咪大史記`;restoreFilterFocus(document.getElementById('view'));menuOpen=false;$('.sidebar').removeClass('open');$('.menu-button').attr('aria-expanded','false');
}
function toast(text){$('.toast').text(text).prop('hidden',false);clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('.toast').prop('hidden',true),2400);}
$(document).on('click','table a[href^="#/"], #record-drawer a[href^="#/"], a[href^="#/artifact-sets"]',event=>{if(event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;const target=detailTargetFromHash(db,event.currentTarget.getAttribute('href'));if(!target)return;event.preventDefault();openDrawer(target,event.currentTarget);});
$(document).on('click','[data-drawer-close]',closeDrawer);
$(document).on('click','[data-drawer-back]',()=>{if(drawerHistory.length>1){drawerHistory.pop();renderDrawer();document.querySelector('[data-drawer-close]').focus({preventScroll:true});}});
$(document).on('submit','#global-search',event=>{event.preventDefault();location.hash=`#/search?q=${encodeURIComponent($('#global-query').val())}`;});
$(document).on('change','.multi-filter-form input[type=checkbox]',event=>{filterFocus={section:event.target.form.dataset.section,name:event.target.name,value:event.target.value,scrollLeft:event.target.closest('.filter-options').scrollLeft};event.target.form.requestSubmit();});
$(document).on('click','.multi-filter-form [data-filter-all]',event=>{const group=event.currentTarget.closest('.multi-filter');const checked=group.querySelectorAll('input:checked');if(!checked.length)return;checked.forEach(input=>input.checked=false);filterFocus={section:event.currentTarget.closest('form').dataset.section,name:event.currentTarget.dataset.filterAll,value:null};event.currentTarget.closest('form').requestSubmit();});
$(document).on('change','#data-mode',event=>setMode(event.target.value));
$(document).on('click','[data-demo]',()=>setMode('demo')).on('click','[data-real]',()=>setMode('real'));
function setMode(value){closeDrawer();mode=value;db=dataSets[mode];saveStorage('catdynasty-mode',mode);team=readStorage(`catdynasty-team-${mode}`,[]);if(!Array.isArray(team))team=[];compare=[];shell();location.hash='#/';render();}
$(document).on('click','[data-menu]',()=>{menuOpen=!menuOpen;$('.sidebar').toggleClass('open',menuOpen);$('.menu-button').attr('aria-expanded',String(menuOpen));});
$(document).on('click','[data-team-add]',event=>{const id=event.currentTarget.dataset.teamAdd;if(team.includes(id))return toast('這位喵將已在隊伍中。');if(team.length>=5)return toast('隊伍已滿，請先移除一位喵將。');team.push(id);saveStorage(`catdynasty-team-${mode}`,team);toast('已加入我的隊伍。');});
$(document).on('submit','.generic-filter',event=>{event.preventDefault();const params=new URLSearchParams(new FormData(event.currentTarget));for(const [key,value] of [...params])if(!value)params.delete(key);if(event.currentTarget.closest('#record-drawer')&&isSetCatalogue(drawerHistory.at(-1))){const target=drawerHistory.at(-1);target.params=params.toString();target.scrollTop=0;renderDrawer();return;}location.hash=`#/${event.currentTarget.dataset.section}?${params}`;});
$(document).on('click','[data-picker-add]',event=>{const id=event.currentTarget.dataset.pickerAdd;if(!get('heroes',id)||team.includes(id)||team.length>=5)return;team.push(id);if(!saveStorage(`catdynasty-team-${mode}`,team))toast('瀏覽器不允許儲存；隊伍會保留至頁面關閉。');render();});
$(document).on('click','[data-team-remove]',event=>{team=team.filter(id=>id!==event.currentTarget.dataset.teamRemove);saveStorage(`catdynasty-team-${mode}`,team);render();});
$(document).on('click','[data-clear-team]',()=>{team=[];saveStorage(`catdynasty-team-${mode}`,team);render();});
$(document).on('click','[data-load-team]',event=>{const record=get('teams',event.currentTarget.dataset.loadTeam);if(!record)return;team=record.heroIds.slice(0,5);saveStorage(`catdynasty-team-${mode}`,team);location.hash='#/team-builder';});
$(document).on('submit','.local-keyword-search',event=>{event.preventDefault();$(event.currentTarget).find('input[type=search]').trigger('input');});
$(document).on('input','#team-query',event=>{const q=event.target.value.trim();$('.picker-row').each(function(){this.hidden=!this.dataset.name.includes(q);});});
$(document).on('submit','#compare-form',event=>{event.preventDefault();try{compare=compareSelection(db,new FormData(event.currentTarget).getAll('heroes'));render();}catch(error){toast(error.message);}});
$(document).on('change','#compare-form input[name="heroes"]',event=>{const checked=$('#compare-form input[name="heroes"]:checked');if(checked.length>3){event.currentTarget.checked=false;toast('最多選擇三位喵將。');}$('#compare-count').text('已選 '+$('#compare-form input[name="heroes"]:checked').length+' / 3 位');});
$(document).on('input','#compare-query',event=>{const q=event.target.value.trim();$('.compare-option').each(function(){this.hidden=!this.dataset.compareName.includes(q);});});
$(document).on('click','[data-clear-compare]',()=>{compare=[];render();});
$(document).on('submit','#requirements-form',event=>{
  event.preventDefault();const values=new FormData(event.currentTarget);
  try{const result=upgradeRequirements(db,values.get('building'),Number(values.get('from')),Number(values.get('to')));$('#requirements-result').html(`<section class="panel"><h2>${result.complete?'已知材料合計':'資料尚未完整'}</h2>${result.missing.length?`<p class="missing-note">缺少等級：${result.missing.map(x=>'Lv.'+x).join('、')}。以下僅列已知部分，不是完整升級需求。</p>`:''}${result.resources.length?result.resources.map(r=>`<div class="relation-row">${recordLink('ingredients',r.id)}<strong>× ${r.amount}</strong></div>`).join(''):`<p class="muted">${result.complete?'所選級別未記錄資源需求。':'無可加總的已知材料。'}</p>`}<p class="spacious">建造時間：${result.buildTime===null?known(null):result.buildTime+' 秒'}</p>${levelTable(result.levels)}</section>`);}catch(error){toast(error.message);}
});
$(document).on('click','[data-copy-code]',async event=>{const code=get('redeem-codes',event.currentTarget.dataset.copyCode);if(!canCopyCode(code,{demo:mode==='demo'}))return;try{await navigator.clipboard.writeText(code.code);toast(codeStatus(code)==='unverified'?'已複製待驗證碼，請於遊戲內確認結果。':'已複製兌換碼。');}catch{toast('無法自動複製，請手動選取兌換碼。');}});
$(document).on('keydown',event=>{if(event.key==='/'&&!/input|textarea|select/i.test(event.target.tagName)){event.preventDefault();$('#global-query').trigger('focus');}if(event.key==='Escape'){menuOpen=false;$('.sidebar').removeClass('open');$('.menu-button').attr('aria-expanded','false');}});
$(document).on('click','.skip-link',event=>{event.preventDefault();$('#main').trigger('focus');document.getElementById('main').scrollIntoView();});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
shell();render();
