import $ from 'jquery';
import './styles.scss';
import {dataSets,categories} from './data.js';
import {escapeHTML as e,safeURL,findById,filterHeroes,searchDatabase,effectIdsForHero,effectsForTeam,heroesForBuilding,recipesForIngredient,codeStatus,upgradeRequirements} from './core.js';

const paths={cat:'M4 9 4 3l5 3h6l5-3v12a8 8 0 0 1-16 0V9Zm4 4h.01M16 13h.01M10 17l2 1 2-1',sword:'m4 20 4-4m-3-3 6 6M9 15 20 4v5L14 15Zm-1-4 5 5',building:'M3 21h18M5 21V9l7-5 7 5v12M9 21v-6h6v6M3 9h18M9 10h.01M15 10h.01',bowl:'M3 12h18a9 9 0 0 1-18 0Zm4 8h10M8 3v5M12 2v6M16 3v5',leaf:'M20 3C8 1 1 10 6 17s16 2 14-14ZM5 20 16 9',vase:'M9 3h6M9 3v4l-4 6c-3 6 1 8 7 8s10-2 7-8l-4-6V3M7 12h10',chair:'M5 11V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v6M3 11v6h18v-6M6 17v4M18 17v4M5 11h14',book:'M3 4h7a2 2 0 0 1 2 2v15a3 3 0 0 0-3-2H3Zm18 0h-7a2 2 0 0 0-2 2v15a3 3 0 0 1 3-2h6Z',people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-2a4 4 0 0 0-3-4M16 3a4 4 0 0 1 0 8',grid:'M3 3h7v7H3ZM14 3h7v7h-7ZM3 14h7v7H3ZM14 14h7v7h-7Z',compare:'M4 4h6v16H4ZM14 4h6v16h-6Z',gift:'M3 8h18v4H3ZM5 12v9h14v-9M12 8v13M12 8S4 7 5 4s7 0 7 4Zm0 0s8-1 7-4-7 0-7 4Z',search:'m21 21-5-5M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16',home:'m3 10 9-7 9 7M5 9v12h14V9M9 21v-8h6v8',menu:'M3 6h18M3 12h18M3 18h18',check:'m5 12 4 4 10-10',external:'M14 3h7v7M10 14 21 3M21 14v7H3V3h7',close:'m6 6 12 12M18 6 6 18'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.book}"/></svg>`;
const link=(key,id='')=>`#/${key}${id?'/'+encodeURIComponent(id):''}`;
const labels={...Object.fromEntries(categories.map(c=>[c.key,c.name])),'redeem-codes':'兌換碼','skill-effects':'技能效果','stages':'攻略','furniture-sets':'家具套裝'};
let mode=readStorage('catdynasty-mode','real');if(!dataSets[mode])mode='real';
let db=dataSets[mode];let team=readStorage(`catdynasty-team-${mode}`,[]);if(!Array.isArray(team))team=[];
let compare=[];let menuOpen=false;
function readStorage(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function saveStorage(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}}
const get=(key,id)=>findById(db,key,id);
function badge(record){if(mode==='demo'||record.gameVersion==='mock')return '<span class="badge demo">示範資料</span>';if(record.gameVersion==='cn')return `<span class="badge reference">陸版${record.verified?'官方參考':'待補資料'}</span>`;if(record.sourceType==='official')return `<span class="badge official">${record.verified?'台版官方確認':'官方部分確認'}</span>`;return `<span class="badge pending">${record.sourceType==='player'?'玩家提供':'待驗證'}</span>`;}
const tag=(text,cls='')=>`<span class="tag ${cls}">${e(text)}</span>`;
const tags=values=>(values||[]).map(v=>tag(v)).join('');
const art=hero=>hero.image?`<img class="hero-art" src="${import.meta.env.BASE_URL}${e(hero.image)}" alt="${e(hero.name)}官方圖鑑" loading="lazy"/>`:`<div class="hero-placeholder">${icon('cat')}<span>圖像待補</span></div>`;
function heroCard(hero){return `<a class="hero-card" href="${link('heroes',hero.id)}"><div class="art-wrap">${art(hero)}<span class="rarity">${e(hero.rarity||'品質待補')}</span></div><div class="card-body"><div class="card-title"><h3>${e(hero.name)}</h3>${icon('external')}</div><p class="hero-meta">${e([hero.type,...hero.role].filter(Boolean).join(' · ')||'職業與定位待核對')}</p><div class="tags">${tag(hero.attribute||'屬性待補')}</div><div class="card-footer">${badge(hero)}<span>${hero.skills.length} 個技能</span></div></div></a>`;}
function empty(title,description,allowDemo=true){return `<div class="empty-state">${icon('book')}<h3>${e(title)}</h3><p>${e(description)}</p>${allowDemo&&mode==='real'?'<button class="button secondary" data-demo>查看功能示範</button>':''}</div>`;}
function title(name,description,extra=''){return `<div class="page-title"><div><h1>${e(name)}</h1>${description?`<p>${e(description)}</p>`:''}</div>${extra}</div>`;}
function sourceBlock(record){const url=safeURL(record.source);return `<section class="source-block"><div>${badge(record)}${record.checkedAt?`<span>核對日期 ${e(record.checkedAt)}</span>`:''}</div>${record.notes?`<p>${e(record.notes)}</p>`:''}${url?`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">查看資料來源 ${icon('external')}</a>`:'<p>來源尚未提供。</p>'}</section>`;}
function known(value){return value===null||value===undefined||value===''?'<span class="muted">尚未確認</span>':e(value);}
function recordLink(key,id){const record=get(key,id);return record?`<a class="inline-link" href="${link(key,id)}">${e(record.name||record.code)}</a>`:'<span class="muted">關聯資料待補</span>';}
function select(name,label,values,value='',id=''){return `<label class="filter-field">${e(label)}<select name="${e(name)}" ${id?`id="${e(id)}"`:''}><option value="">全部${e(label)}</option>${values.map(v=>{const [val,text]=Array.isArray(v)?v:[v,v];return `<option value="${e(val)}"${val===value?' selected':''}>${e(text)}</option>`;}).join('')}</select></label>`;}
function shell(){const groups=['資料庫','攻略','工具','其他'];$('#app').html(`<aside class="sidebar ${menuOpen?'open':''}" aria-label="主導覽"><a class="brand" href="#/"><span class="seal">喵</span><div><strong>喵國資料庫</strong><span>小貓咪大史記</span></div></a><nav><a class="nav-link home-link" href="#/">${icon('home')}<span>資料庫總覽</span></a>${groups.map(group=>`<div class="nav-group"><span class="nav-label">${group}</span>${categories.filter(c=>c.group===group).map(c=>`<a class="nav-link" data-nav="${c.key}" href="${link(c.key)}">${icon(c.icon)}<span>${c.name}</span></a>`).join('')}</div>`).join('')}</nav><div class="sidebar-foot"><span class="edition">台版為主 · 陸版參考</span><p>非官方攻略資料庫<br>每筆資訊保留來源與核對狀態</p></div></aside><div class="workspace"><header class="topbar"><button class="icon-button menu-button" aria-label="開啟導覽" aria-expanded="${menuOpen}" data-menu>${icon('menu')}</button><form class="global-search" id="global-search" role="search">${icon('search')}<label class="sr-only" for="global-query">全站搜尋</label><input id="global-query" placeholder="搜尋喵將、效果、建築、食材…" autocomplete="off"/><button type="submit" class="search-submit">搜尋</button></form><label class="mode-control">資料模式<select id="data-mode"><option value="real"${mode==='real'?' selected':''}>已收錄資料</option><option value="demo"${mode==='demo'?' selected':''}>功能示範</option></select></label></header>${mode==='demo'?'<div class="demo-banner"><strong>功能示範模式</strong>　以下配方、加成與兌換碼均為測試範例，非遊戲資料。<button data-real>返回已收錄資料</button></div>':''}<main id="main" tabindex="-1"><div id="breadcrumbs" class="breadcrumbs"></div><div id="view"></div></main><footer class="site-footer"><span>喵國資料庫 · 非官方</span><span>台陸版本差異以遊戲內資訊為準 · 角色圖像著作權屬原權利人</span></footer></div><div class="toast" role="status" aria-live="polite" hidden></div>`);}
function home(){const complete=db.heroes.filter(h=>h.skills.length);const officialCount=db.heroes.filter(h=>h.verified).length;return `${title('喵國攻略資料庫','找喵將、查技能，也找得到它們之間的關聯。', '<span class="edition-pill">資料整理中 · 2026.10.01</span>')}<div class="metrics"><a href="#/heroes"><span>已收錄喵將</span><strong>${db.heroes.length}<small>位</small></strong></a><a href="#/skills"><span>已收錄技能</span><strong>${db.skills.length}<small>項</small></strong></a><a href="#/buildings"><span>建築資料</span><strong>${db.buildings.length}<small>座</small></strong></a><a href="#/codes"><span>已核實有效碼</span><strong>${db['redeem-codes'].filter(c=>codeStatus(c)==='active').length}<small>組</small></strong></a></div><section class="quick-panel"><div><span class="eyebrow">快速查詢</span><h2>從你想找的效果開始</h2></div><div class="quick-tags">${[['heal','治療'],['revive','復活'],['burn','灼燒'],['true_damage','真實傷害'],['dispel','驅散']].map(([id,name])=>`<a href="#/heroes?effect=${id}">${icon(id==='true_damage'?'sword':'leaf')}${name}</a>`).join('')}<a href="#/buildings">${icon('building')}建築加速</a></div></section><div class="section-heading"><div><span class="eyebrow">喵將圖鑑</span><h2>先了解你的喵將</h2></div><a class="text-link" href="#/heroes">查看全部 ${db.heroes.length} 位</a></div><div class="hero-grid">${(complete.length?complete:db.heroes).slice(0,4).map(heroCard).join('')}</div><div class="home-bottom"><section class="panel"><div class="section-heading"><h2>資料庫索引</h2></div><div class="index-grid">${categories.filter(c=>c.group==='資料庫').map(c=>`<a href="${link(c.key)}">${icon(c.icon)}<span>${c.name}</span><small>${(db[c.key]||[]).length} 筆</small></a>`).join('')}</div></section><section class="panel update-panel"><span class="eyebrow">資料進度</span><h2>每一筆資料，都有出處</h2><p>目前收錄 ${officialCount} 位陸版官方圖鑑參考。台版技能數值、建築升級與食譜材料持續等待核對。</p><div class="progress-track"><span style="width:${db.heroes.length?officialCount/db.heroes.length*100:0}%"></span></div><span class="muted">有完整技能的喵將：${complete.length} / ${db.heroes.length}</span><a class="text-link" href="#/heroes?version=tw">查看台版資料</a></section></div>`;}
function heroTable(heroes){
  return `<div class="hero-table-scroll" role="region" aria-label="喵將圖鑑表格，可左右捲動" tabindex="0"><table class="hero-table"><caption class="sr-only">喵將屬性與資料版本一覽</caption><thead><tr>${['喵將','品質','職業','定位','屬性','六藝重點','技能','建築加成','資料版本'].map(label=>`<th scope="col">${label}</th>`).join('')}</tr></thead><tbody>${heroes.map(hero=>`<tr><th scope="row"><a class="hero-name-link" href="${link('heroes',hero.id)}">${e(hero.name)}</a><a class="hero-detail-link" href="${link('heroes',hero.id)}">查看詳細資料</a></th><td>${known(hero.rarity)}</td><td>${known(hero.type)}</td><td><div class="tags">${tags(hero.role)||known(null)}</div></td><td>${known(hero.attribute)}</td><td>${hero.sixArts.length?e(hero.sixArts.join('、')):known(null)}</td><td>${hero.skills.length?`<a class="inline-link" href="${link('heroes',hero.id)}">${hero.skills.length} 個技能</a>`:known(null)}</td><td>${hero.buildingBonuses.length?hero.buildingBonuses.map(b=>recordLink('buildings',b.buildingId)).join('<br>'):known(null)}</td><td>${badge(hero)}</td></tr>`).join('')}</tbody></table></div>`;
}
function heroList(params){const filters=Object.fromEntries(params);const heroes=filterHeroes(db,filters);const rarities=[...new Set(db.heroes.map(h=>h.rarity).filter(Boolean))];const roles=[...new Set(db.heroes.flatMap(h=>h.role))];return `${title('喵將圖鑑','用表格查閱喵將屬性，依定位、技能效果與版本篩選。')}<form class="filter-bar" id="hero-filters"><label class="filter-field query-field">名稱或關聯<input name="query" value="${e(filters.query||'')}" placeholder="例如：太醫院、治療"/></label>${select('rarity','品質',rarities,filters.rarity)}${select('role','定位',roles,filters.role)}${select('effect','技能效果',db['skill-effects'].filter(x=>db.skills.some(s=>s.effects.some(v=>v.type===x.id))).map(x=>[x.id,x.name]),filters.effect)}${select('version','版本',[['tw','台版'],['cn','陸版參考'],['mock','示範']],filters.version)}<button class="button" type="submit">套用篩選</button><a class="text-link" href="#/heroes">重設</a></form><div class="result-summary" role="status">找到 <strong>${heroes.length}</strong> 位喵將 <span>未知欄位保留待補 · 表格可左右滑動</span></div>${heroes.length?heroTable(heroes):empty('沒有符合條件的喵將','試著放寬篩選，或更換關鍵字。',false)}`;}
function heroDetail(hero){return `${title(hero.name,hero.description,`<button class="button" data-team-add="${e(hero.id)}">加入我的隊伍</button>`)}<div class="hero-detail-layout"><div class="portrait-panel">${art(hero)}<a href="${hero.image?import.meta.env.BASE_URL+e(hero.image):hero.source}" target="_blank" rel="noopener noreferrer">查看官方完整圖鑑 ${icon('external')}</a></div><div><section class="panel"><div class="detail-summary">${badge(hero)}${tags(hero.role)}</div><dl class="facts"><div><dt>品質</dt><dd>${known(hero.rarity)}</dd></div><div><dt>職業</dt><dd>${known(hero.type)}</dd></div><div><dt>屬性</dt><dd>${known(hero.attribute)}</dd></div><div><dt>六藝重點</dt><dd>${hero.sixArts.length?e(hero.sixArts.join('、')):known(null)}</dd></div></dl></section><section class="panel"><h2>技能</h2>${hero.skills.length?hero.skills.map(id=>{const s=get('skills',id);return `<article class="skill-row"><div><h3><a href="${link('skills',s.id)}">${e(s.name)}</a></h3>${tag(s.type)}</div><p>${e(s.description)}</p><div class="tags">${s.effects.map(v=>tag(get('skill-effects',v.type)?.name||v.type)).join('')}</div></article>`;}).join(''):empty('技能資料待補','尚未取得可核對的台版技能資料。',false)}</section></div></div><div class="two-columns"><section class="panel"><h2>建設能力</h2>${hero.buildingBonuses.length?hero.buildingBonuses.map(b=>`<div class="relation-row"><div>${recordLink('buildings',b.buildingId)}<p>${e(b.description)}</p></div><strong>${b.value===null?'數值待補':e(b.value)+'%'}</strong></div>`).join(''):empty('建築加成尚未確認','取得遊戲內資料後再補入。',false)}</section><section class="panel"><h2>推薦搭配</h2>${db.teams.filter(t=>t.heroIds.includes(hero.id)).map(t=>`<div class="relation-row"><div>${recordLink('teams',t.id)}<p>${t.heroIds.map(id=>recordLink('heroes',id)).join(' · ')}</p></div></div>`).join('')||'<p class="muted">尚未收錄推薦隊伍。</p>'}</section></div>${sourceBlock(hero)}`;}
function recordCard(key,record){
  const category=categories.find(c=>c.key===key);
  return `<a class="record-card" href="${link(key,record.id)}"><div class="record-icon">${icon(category?.icon||'book')}</div><div><div class="card-title"><h3>${e(record.name||record.code)}</h3>${icon('external')}</div><p>${e(record.description||'詳細資料待補。')}</p><div class="tags">${tags(record.effectTags||[record.type,record.rarity].filter(Boolean))}</div><div class="card-footer">${badge(record)}</div></div></a>`;
}
function recordList(key,params){
  const query=params.get('query')||'';const type=params.get('type')||'';const effect=params.get('effect')||'';
  const records=db[key]||[];const hits=query?new Set(searchDatabase(db,query).filter(r=>r.key===key).map(r=>r.record.id)):null;
  const results=records.filter(r=>(!hits||hits.has(r.id))&&(!type||r.type===type)&&(!effect||r.effectTags?.includes(effect)));
  const types=[...new Set(records.map(r=>r.type).filter(Boolean))];const effects=[...new Set(records.flatMap(r=>r.effectTags||[]))];
  const description={buildings:'查建築功能、升級需求與可加速的喵將。',recipes:'從食譜看材料，從材料反查能製作的食譜。',ingredients:'查取得方式、來源建築與可製作食譜。',artifacts:'依效果標籤查古寶、強化資料與適用隊伍。',furniture:'查擺放空間、家具套裝與屬性效果。',skills:'依技能查效果與擁有該技能的喵將。',teams:'收錄有來源的推薦搭配，並可載入隊伍編輯器。','furniture-sets':'查套裝成員與件數效果。','skill-effects':'以標準化效果標籤反查技能與喵將。'}[key];
  return `${title(labels[key]||key,description,key==='furniture'?'<a class="button secondary" href="#/furniture-sets">家具套裝</a>':key==='skills'?'<a class="button secondary" href="#/skill-effects">效果索引</a>':'')}<form class="filter-bar generic-filter" data-section="${key}"><label class="filter-field query-field">名稱或關聯<input name="query" value="${e(query)}" placeholder="輸入關鍵字"/></label>${types.length?select('type','類型',types,type):''}${effects.length?select('effect','效果',effects,effect):''}<button class="button" type="submit">套用篩選</button><a class="text-link" href="${link(key)}">重設</a></form><div class="result-summary" role="status">找到 <strong>${results.length}</strong> 筆資料</div>${results.length?`<div class="record-grid">${results.map(r=>recordCard(key,r)).join('')}</div>`:empty('尚無可核對的資料',mode==='real'?'此分類的資料結構與查詢功能已備妥，等取得遊戲資料後即可補入。':'沒有符合條件的示範資料。')}`;
}
function levelTable(levels){return levels.length?`<div class="table-scroll"><table><thead><tr><th>等級</th><th>主城條件</th><th>資源</th><th>時間</th><th>資料狀態</th></tr></thead><tbody>${levels.sort((a,b)=>a.level-b.level).map(l=>`<tr><td>Lv.${l.level}</td><td>${known(l.requirements.cityLevel)}</td><td>${l.requirements.resources.length?l.requirements.resources.map(r=>`${recordLink('ingredients',r.id)} × ${r.amount}`).join('<br>'):'無資源條件記錄'}</td><td>${l.buildTime===null?known(null):`${e(l.buildTime)} 秒`}</td><td>${badge(l)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">各級解鎖條件、材料與建造時間尚未確認。</p>';}
function buildingDetail(record){
  const heroes=heroesForBuilding(db,record.id);const recipes=db.recipes.filter(r=>r.buildingId===record.id);
  return `${title(record.name,record.description)}<div class="two-columns"><section class="panel"><h2>建築資訊</h2><dl class="facts"><div><dt>類型</dt><dd>${known(record.type)}</dd></div><div><dt>主城解鎖等級</dt><dd>${known(record.unlock.cityLevel)}</dd></div><div><dt>其他解鎖條件</dt><dd>${known(record.unlock.condition)}</dd></div><div><dt>已知升級資料</dt><dd>${record.levels.length} 個等級</dd></div></dl></section><section class="panel"><h2>可加速喵將</h2>${heroes.length?heroes.map(h=>{const b=h.buildingBonuses.find(x=>x.buildingId===record.id);return `<div class="relation-row"><div>${recordLink('heroes',h.id)}<p>${e(b.description)}</p></div><strong>${b.value===null?'數值待補':e(b.value)+'%'}</strong></div>`;}).join(''):'<p class="muted">加速喵將尚未確認。</p>'}</section></div><section class="panel"><div class="section-heading"><h2>升級條件</h2><a class="text-link" href="#/requirements?building=${e(record.id)}">計算升級需求</a></div>${levelTable(db['building-levels'].filter(l=>l.buildingId===record.id))}</section><div class="two-columns"><section class="panel"><h2>生產內容</h2>${record.production.length?record.production.map(id=>`<div class="relation-row">${recordLink('ingredients',id)}</div>`).join(''):'<p class="muted">生產內容尚未確認。</p>'}</section><section class="panel"><h2>相關食譜</h2>${recipes.length?recipes.map(r=>`<div class="relation-row">${recordLink('recipes',r.id)}</div>`).join(''):'<p class="muted">尚未收錄相關食譜。</p>'}</section></div>${sourceBlock(record)}`;
}
function recipeDetail(record){return `${title(record.name,record.description)}<div class="two-columns"><section class="panel"><h2>配方材料</h2>${record.ingredients.length?record.ingredients.map(i=>`<div class="relation-row">${recordLink('ingredients',i.ingredientId)}<strong>× ${known(i.amount)}</strong></div>`).join(''):'<p class="muted">配方材料尚未確認。</p>'}</section><section class="panel"><h2>製作條件</h2><dl class="facts"><div><dt>製作建築</dt><dd>${record.buildingId?recordLink('buildings',record.buildingId):known(null)}</dd></div><div><dt>產出數量</dt><dd>${known(record.outputAmount)}</dd></div><div><dt>製作時間</dt><dd>${record.craftTime===null?known(null):e(record.craftTime)+' 秒'}</dd></div><div><dt>解鎖條件</dt><dd>${known(record.unlock)}</dd></div></dl></section></div>${sourceBlock(record)}`;}
function ingredientDetail(record){const recipes=recipesForIngredient(db,record.id);return `${title(record.name,record.description)}<div class="two-columns"><section class="panel"><h2>可以製作的食譜</h2>${recipes.length?recipes.map(r=>`<div class="relation-row">${recordLink('recipes',r.id)}<span>需 ${known(r.ingredients.find(i=>i.ingredientId===record.id).amount)} 份</span></div>`).join(''):'<p class="muted">尚未收錄使用此食材的食譜。</p>'}</section><section class="panel"><h2>取得來源</h2>${record.obtainedFrom.length?record.obtainedFrom.map(id=>`<div class="relation-row">${recordLink('buildings',id)}</div>`).join(''):'<p class="muted">取得方式尚未確認。</p>'}</section></div>${sourceBlock(record)}`;}
const statLabels={health:'生命',crit_up:'暴擊提升',speed_up:'速度提升',attack_up:'攻擊提升',damage_reduction:'減傷'};
function statsTable(effects){return effects.length?effects.map(effect=>`<div class="relation-row"><span>${e(get('skill-effects',effect.type)?.name||statLabels[effect.type]||effect.type)}</span><strong>${effect.value===null?'數值待補':e(effect.value)+(effect.unit==='percent'?'%':'')}</strong></div>`).join(''):'<p class="muted">屬性效果尚未確認。</p>';}
function artifactDetail(record){const levels=db['artifact-levels'].filter(l=>l.artifactId===record.id);return `${title(record.name,record.description)}<div class="two-columns"><section class="panel"><h2>基礎效果</h2><p>品質：${known(record.rarity)}</p><div class="tags spacious">${tags(record.effectTags)}</div>${statsTable(record.effects)}</section><section class="panel"><h2>取得方式</h2>${record.acquisition.length?`<ul>${record.acquisition.map(x=>`<li>${e(x)}</li>`).join('')}</ul>`:'<p class="muted">取得方式尚未確認。</p>'}</section></div><div class="two-columns"><section class="panel"><h2>適用喵將與隊伍</h2>${[...record.heroIds.map(id=>recordLink('heroes',id)),...record.teamIds.map(id=>recordLink('teams',id))].map(x=>`<div class="relation-row">${x}</div>`).join('')||'<p class="muted">尚未收錄有來源的搭配。</p>'}</section><section class="panel"><h2>升級與強化</h2>${levels.length?levels.map(l=>`<h3>Lv.${l.level}</h3>${statsTable(l.effects)}<p class="muted">${l.requirements.length?l.requirements.map(r=>e(r.id)+' × '+r.amount).join('、'):'強化材料尚未確認。'}</p>`).join(''):'<p class="muted">強化效果與材料尚未確認。</p>'}</section></div>${sourceBlock(record)}`;}
function furnitureDetail(record){const set=get('furniture-sets',record.setId);return `${title(record.name,record.description)}<div class="two-columns"><section class="panel"><h2>家具資訊</h2><dl class="facts"><div><dt>類型</dt><dd>${known(record.type)}</dd></div><div><dt>品質</dt><dd>${known(record.rarity)}</dd></div><div><dt>擺放位置</dt><dd>${record.placement.length?e(record.placement.join('、')):known(null)}</dd></div><div><dt>套裝</dt><dd>${set?recordLink('furniture-sets',set.id):known(null)}</dd></div></dl><div class="tags spacious">${tags(record.effectTags)}</div>${statsTable(record.effects)}</section><section class="panel"><h2>取得方式與相關空間</h2><p>${record.acquisition.length?e(record.acquisition.join('、')):'取得方式尚未確認。'}</p><div class="tags spacious">${tags(record.spaceTags)}</div>${record.buildingIds.map(id=>`<div class="relation-row">${recordLink('buildings',id)}</div>`).join('')}</section></div>${set?`<section class="panel"><h2>${recordLink('furniture-sets',set.id)}</h2><p>${set.furnitureIds.map(id=>recordLink('furniture',id)).join(' · ')}</p>${set.bonuses.map(b=>`<div class="relation-row"><strong>${b.pieces} 件套</strong><p>${e(b.description)}</p>${tags(b.effectTags)}</div>`).join('')}</section>`:''}${sourceBlock(record)}`;}
function setDetail(record){return `${title(record.name,'集齊套裝件數後，查看對應效果。')}<section class="panel"><h2>套裝成員</h2><div class="record-grid">${record.furnitureIds.map(id=>recordCard('furniture',get('furniture',id))).join('')}</div></section><section class="panel"><h2>套裝效果</h2>${record.bonuses.map(b=>`<h3>${b.pieces} 件套</h3><p>${e(b.description)}</p>${statsTable(b.effects)}`).join('')}</section>${sourceBlock(record)}`;}
function skillDetail(record){const heroes=db.heroes.filter(h=>h.skills.includes(record.id));return `${title(record.name,record.description)}<section class="panel"><dl class="facts"><div><dt>技能類型</dt><dd>${known(record.type)}</dd></div><div><dt>作用目標</dt><dd>${known(record.target)}</dd></div><div><dt>冷卻</dt><dd>${known(record.cooldown)}</dd></div></dl></section><section class="panel"><h2>技能效果</h2><div class="tags spacious">${record.effects.map(v=>`<a href="#/heroes?effect=${e(v.type)}">${tag(get('skill-effects',v.type)?.name||v.type)}</a>`).join('')}</div><p class="muted">未公開的倍率、機率與持續時間保留未知；技能升級差异請參閱原圖鑑。</p></section><section class="panel"><h2>擁有此技能的喵將</h2><div class="hero-grid">${heroes.map(heroCard).join('')}</div></section>${sourceBlock(record)}`;}
function effectDetail(record){const heroes=db.heroes.filter(h=>effectIdsForHero(db,h).includes(record.id));const skills=db.skills.filter(s=>s.effects.some(v=>v.type===record.id));return `${title(record.name,'依技能效果反查喵將與技能。')}<section class="panel"><h2>擁有此效果的喵將</h2><div class="hero-grid">${heroes.map(heroCard).join('')||'<p class="muted">尚未收錄。</p>'}</div></section><section class="panel"><h2>相關技能</h2><div class="record-grid">${skills.map(s=>recordCard('skills',s)).join('')}</div></section>`;}
function teamDetail(record){return `${title(record.name,record.description,`<button class="button" data-load-team="${e(record.id)}">載入隊伍編輯器</button>`)}<div class="hero-grid team-grid">${record.heroIds.map(id=>heroCard(get('heroes',id))).join('')}</div><section class="panel"><h2>已知隊伍效果</h2><div class="tags">${effectsForTeam(db,record.heroIds).map(id=>tag(get('skill-effects',id)?.name||id)).join('')||'<p class="muted">技能資料尚未完整，無法彙總。</p>'}</div><p class="muted spacious">效果彙總僅包含已收錄技能，不代表完整隊伍能力。</p></section>${sourceBlock(record)}`;}
function searchView(params){const query=params.get('q')||'';const category=params.get('category')||'';const all=searchDatabase(db,query);const results=all.filter(r=>!category||r.key===category);const foundKeys=[...new Set(all.map(r=>r.key))];return `${title('全站搜尋',query?`「${query}」的名稱、技能與關聯查詢結果。`:'輸入關鍵字搜尋整個資料庫。')}<form class="filter-bar" id="search-form"><label class="filter-field query-field">關鍵字<input name="q" value="${e(query)}" placeholder="例如：治療、太醫院、暴擊"/></label>${select('category','分類',foundKeys.map(k=>[k,labels[k]||k]),category)}<button class="button" type="submit">搜尋</button></form><div class="result-summary" role="status">找到 <strong>${results.length}</strong> 筆資料</div><div class="search-results">${results.length?results.map(({key,record,related})=>`<a class="search-result" href="${link(key==='redeem-codes'?'codes':key==='stages'?'guides':key,record.id)}"><div><span class="eyebrow">${e(labels[key]||key)}${related?' · 關聯符合':''}</span><h3>${e(record.name||record.code)}</h3><p>${e(record.description||record.notes||'查看詳細資料')}</p></div>${badge(record)}</a>`).join(''):empty(query?'沒有符合的資料':'開始查詢','可搜尋角色名、技能效果、建築、食材、古寶與家具。',false)}</div>`;}
function codesView(params,id){const status=params.get('status')||'';const codes=db['redeem-codes'].filter(c=>(!id||c.id===id)&&(!status||codeStatus(c)===status));const statusNames={active:'已核實有效',expired:'已失效',unverified:'有效性待驗證',upcoming:'尚未開始'};return `${title('兌換碼','僅把有遊戲驗證紀錄的兌換碼列為有效。')}<div class="tab-bar">${[['','全部'],['active','有效'],['unverified','待驗證'],['expired','已失效']].map(([key,name])=>`<a class="${status===key?'selected':''}" href="#/codes${key?'?status='+key:''}">${name}</a>`).join('')}</div>${codes.length?codes.map(c=>`<section class="panel code-card"><div><span class="badge ${codeStatus(c)==='active'?'official':'pending'}">${statusNames[codeStatus(c)]}</span><h2 class="code-text">${e(c.code)}</h2><p>${e(c.rewards.join('、')||'獎勵尚未確認')}</p><p class="muted">有效期限：${known(c.endDate)} · 實測日期：${known(c.lastTestedAt)}</p></div><button class="button secondary" data-copy-code="${e(c.id)}" ${mode==='demo'||codeStatus(c)!=='active'?'disabled':''}>${mode==='demo'?'示範碼不提供複製':'複製兌換碼'}</button>${sourceBlock(c)}</section>`).join(''):empty('尚無符合條件的兌換碼','目前沒有已核實的台版有效兌換碼。陸版兌換碼不會列為台版有效碼。')}`;}
function guidesView(params,id){const type=params.get('type')||'';const records=db.stages.filter(s=>(!id||s.id===id)&&(!type||s.type===type));return `${title('關卡與系統攻略','有來源的關卡、Boss 與系統資料。')}<div class="tab-bar">${[['','全部'],['關卡','關卡'],['Boss','Boss'],['系統','系統']].map(([key,name])=>`<a class="${type===key?'selected':''}" href="#/guides${key?'?type='+key:''}">${name}</a>`).join('')}</div>${records.length?records.map(r=>`<section class="panel"><h2>${e(r.name)}</h2><div class="tags spacious">${tag(r.type)}${badge(r)}</div><p>${e(r.description)}</p><p class="spacious">${r.heroIds.map(id=>recordLink('heroes',id)).join(' · ')}</p><p>${r.teamIds.map(id=>recordLink('teams',id)).join(' · ')}</p>${sourceBlock(r)}</section>`).join(''):empty('攻略資料整理中','關卡與 Boss 攻略會在取得可靠遊戲資料後加入。')}`;}
function teamBuilder(){team=team.filter(id=>get('heroes',id)).slice(0,5);const effects=effectsForTeam(db,team);return `${title('隊伍編輯器','選擇最多五位喵將，查看已知技能效果。','<button class="button secondary" data-clear-team>清空隊伍</button>')}<section class="panel"><div class="section-heading"><h2>我的隊伍</h2><span class="muted">${team.length} / 5 位 · 儲存於這台裝置</span></div><div class="team-slots">${Array.from({length:5},(_,i)=>{const h=get('heroes',team[i]);return h?`<div class="team-slot filled"><div class="slot-art">${art(h)}</div><h3>${e(h.name)}</h3>${tags(h.role)}<button class="text-link" data-team-remove="${e(h.id)}">移除</button></div>`:`<div class="team-slot"><span class="slot-number">0${i+1}</span>${icon('cat')}<p>選擇喵將</p></div>`;}).join('')}</div><div class="team-effect-row"><strong>隊伍效果</strong><div class="tags">${effects.map(id=>tag(get('skill-effects',id)?.name||id)).join('')||'<span class="muted">加入有技能資料的喵將後顯示。</span>'}</div></div><p class="muted">僅彙總已知技能；不推測強度，也不把陸版效果視為台版確認。</p></section><section class="panel"><div class="section-heading"><h2>選擇喵將</h2><label class="sr-only" for="team-query">搜尋可選喵將</label><input class="standalone-input" id="team-query" placeholder="輸入喵將名稱"/></div><div class="hero-picker">${db.heroes.map(h=>`<div class="picker-row" data-name="${e(h.name)}"><div><strong>${e(h.name)}</strong><p>${e(h.role.join(' · ')||'定位待補')}</p></div>${badge(h)}<button class="button secondary" data-picker-add="${e(h.id)}" ${team.includes(h.id)||team.length>=5?'disabled':''}>${team.includes(h.id)?'已加入':'加入'}</button></div>`).join('')}</div></section>`;}
function compareView(){const heroes=compare.map(id=>get('heroes',id)).filter(Boolean);return `${title('喵將比較','比較已知定位、技能效果與建設能力。')}<form id="compare-form" class="filter-bar"><label class="filter-field query-field">選擇最多三位喵將<select name="heroes" multiple size="5">${db.heroes.map(h=>`<option value="${e(h.id)}" ${compare.includes(h.id)?'selected':''}>${e(h.name)}</option>`).join('')}</select></label><button class="button" type="submit">開始比較</button></form>${heroes.length?`<section class="panel table-scroll"><table class="compare-table"><thead><tr><th>比較項目</th>${heroes.map(h=>`<th>${recordLink('heroes',h.id)}</th>`).join('')}</tr></thead><tbody>${[['資料狀態',h=>badge(h)],['品質',h=>known(h.rarity)],['職業',h=>known(h.type)],['定位',h=>tags(h.role)||known(null)],['屬性',h=>known(h.attribute)],['六藝',h=>tags(h.sixArts)||known(null)],['技能效果',h=>tags(effectIdsForHero(db,h).map(id=>get('skill-effects',id)?.name||id))||known(null)],['建築加成',h=>h.buildingBonuses.map(b=>recordLink('buildings',b.buildingId)).join('、')||known(null)]].map(([label,fn])=>`<tr><th>${label}</th>${heroes.map(h=>`<td>${fn(h)}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`:empty('選擇要比較的喵將','桌面可按住 Ctrl 或 Command 多選；手機可使用多選清單。',false)}`;}
function requirementsView(params){const building=params.get('building')||db.buildings[0]?.id;return `${title('建築需求','累加已收錄等級的材料；缺少資料時顯示缺漏等級。')}<form id="requirements-form" class="filter-bar"><label class="filter-field query-field">建築<select name="building" required>${db.buildings.map(b=>`<option value="${e(b.id)}" ${building===b.id?'selected':''}>${e(b.name)}</option>`).join('')}</select></label><label class="filter-field">目前等級<input name="from" type="number" min="0" max="999" value="0" required/></label><label class="filter-field">目標等級<input name="to" type="number" min="1" max="1000" value="2" required/></label><button class="button" ${!db.buildings.length?'disabled':''}>計算需求</button></form><div id="requirements-result">${empty('選擇建築與等級','沒有資料的級別會列為待補，不會計算成零。',false)}</div>`;}
function detail(key,record){const views={buildings:buildingDetail,recipes:recipeDetail,ingredients:ingredientDetail,artifacts:artifactDetail,furniture:furnitureDetail,'furniture-sets':setDetail,skills:skillDetail,'skill-effects':effectDetail,teams:teamDetail};return views[key]?.(record)||empty('找不到詳細頁','請返回資料庫索引。',false);}
function render(){
  db=dataSets[mode];const url=new URL(location.hash.slice(1)||'/', 'https://wiki.local');const [section='',encodedId='']=url.pathname.split('/').filter(Boolean);let id;try{id=decodeURIComponent(encodedId);}catch{id=encodedId;}
  const current=categories.find(c=>c.key===section);$('.nav-link').removeClass('active');$('.nav-link').filter(function(){return section?this.dataset.nav===section:this.classList.contains('home-link');}).addClass('active');
  $('#breadcrumbs').html(`<a href="#/">總覽</a>${section?`<span>/</span><a href="${link(section)}">${e(current?.name||labels[section]||'搜尋')}</a>`:''}${id?'<span>/</span><span>詳細資料</span>':''}`);
  let html;
  if(!section)html=home();
  else if(section==='heroes')html=id?(get('heroes',id)?heroDetail(get('heroes',id)):empty('找不到喵將','此連結可能不屬於目前資料模式。')):heroList(url.searchParams);
  else if(section==='search')html=searchView(url.searchParams);
  else if(section==='codes')html=codesView(url.searchParams,id);
  else if(section==='guides')html=guidesView(url.searchParams,id);
  else if(section==='team-builder')html=teamBuilder();
  else if(section==='compare')html=compareView();
  else if(section==='requirements')html=requirementsView(url.searchParams);
  else if(db[section])html=id?(get(section,id)?detail(section,get(section,id)):empty('找不到資料','此連結可能不屬於目前資料模式。')):recordList(section,url.searchParams);
  else html=empty('找不到頁面','請從左側導覽選擇資料分類。',false);
  $('#view').html(html);document.title=`${current?.name||labels[section]||'喵國資料庫'}｜小貓咪大史記`;menuOpen=false;$('.sidebar').removeClass('open');$('.menu-button').attr('aria-expanded','false');
}
function toast(text){$('.toast').text(text).prop('hidden',false);clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('.toast').prop('hidden',true),2400);}
$(document).on('submit','#global-search',event=>{event.preventDefault();location.hash=`#/search?q=${encodeURIComponent($('#global-query').val())}`;});
$(document).on('submit','#hero-filters',event=>{event.preventDefault();const params=new URLSearchParams(new FormData(event.currentTarget));for(const [key,value] of [...params])if(!value)params.delete(key);location.hash=`#/heroes?${params}`;});
$(document).on('change','#data-mode',event=>setMode(event.target.value));
$(document).on('click','[data-demo]',()=>setMode('demo')).on('click','[data-real]',()=>setMode('real'));
function setMode(value){mode=value;db=dataSets[mode];saveStorage('catdynasty-mode',mode);team=readStorage(`catdynasty-team-${mode}`,[]);if(!Array.isArray(team))team=[];compare=[];shell();location.hash='#/';render();}
$(document).on('click','[data-menu]',()=>{menuOpen=!menuOpen;$('.sidebar').toggleClass('open',menuOpen);$('.menu-button').attr('aria-expanded',String(menuOpen));});
$(document).on('click','[data-team-add]',event=>{const id=event.currentTarget.dataset.teamAdd;if(team.includes(id))return toast('這位喵將已在隊伍中。');if(team.length>=5)return toast('隊伍已滿，請先移除一位喵將。');team.push(id);saveStorage(`catdynasty-team-${mode}`,team);toast('已加入我的隊伍。');});
$(document).on('submit','.generic-filter',event=>{event.preventDefault();const params=new URLSearchParams(new FormData(event.currentTarget));for(const [key,value] of [...params])if(!value)params.delete(key);location.hash=`#/${event.currentTarget.dataset.section}?${params}`;});
$(document).on('submit','#search-form',event=>{event.preventDefault();location.hash=`#/search?${new URLSearchParams(new FormData(event.currentTarget))}`;});
$(document).on('click','[data-picker-add]',event=>{const id=event.currentTarget.dataset.pickerAdd;if(!get('heroes',id)||team.includes(id)||team.length>=5)return;team.push(id);if(!saveStorage(`catdynasty-team-${mode}`,team))toast('瀏覽器不允許儲存；隊伍會保留至頁面關閉。');render();});
$(document).on('click','[data-team-remove]',event=>{team=team.filter(id=>id!==event.currentTarget.dataset.teamRemove);saveStorage(`catdynasty-team-${mode}`,team);render();});
$(document).on('click','[data-clear-team]',()=>{team=[];saveStorage(`catdynasty-team-${mode}`,team);render();});
$(document).on('click','[data-load-team]',event=>{const record=get('teams',event.currentTarget.dataset.loadTeam);if(!record)return;team=record.heroIds.slice(0,5);saveStorage(`catdynasty-team-${mode}`,team);location.hash='#/team-builder';});
$(document).on('input','#team-query',event=>{const q=event.target.value.trim();$('.picker-row').each(function(){this.hidden=!this.dataset.name.includes(q);});});
$(document).on('submit','#compare-form',event=>{event.preventDefault();const ids=new FormData(event.currentTarget).getAll('heroes');if(ids.length>3)return toast('最多選擇三位喵將。');compare=ids;render();});
$(document).on('submit','#requirements-form',event=>{
  event.preventDefault();const values=new FormData(event.currentTarget);
  try{const result=upgradeRequirements(db,values.get('building'),Number(values.get('from')),Number(values.get('to')));$('#requirements-result').html(`<section class="panel"><h2>${result.complete?'已知材料合計':'資料尚未完整'}</h2>${result.missing.length?`<p class="missing-note">缺少等級：${result.missing.map(x=>'Lv.'+x).join('、')}。以下僅列已知部分，不是完整升級需求。</p>`:''}${result.resources.length?result.resources.map(r=>`<div class="relation-row">${recordLink('ingredients',r.id)}<strong>× ${r.amount}</strong></div>`).join(''):`<p class="muted">${result.complete?'所選級別未記錄資源需求。':'無可加總的已知材料。'}</p>`}<p class="spacious">建造時間：${result.buildTime===null?known(null):result.buildTime+' 秒'}</p>${levelTable(result.levels)}</section>`);}catch(error){toast(error.message);}
});
$(document).on('click','[data-copy-code]',async event=>{const code=get('redeem-codes',event.currentTarget.dataset.copyCode);if(!code||mode==='demo'||codeStatus(code)!=='active')return;try{await navigator.clipboard.writeText(code.code);toast('已複製兌換碼。');}catch{toast('無法自動複製，請手動選取兌換碼。');}});
$(document).on('keydown',event=>{if(event.key==='/'&&!/input|textarea|select/i.test(event.target.tagName)){event.preventDefault();$('#global-query').trigger('focus');}if(event.key==='Escape'){menuOpen=false;$('.sidebar').removeClass('open');$('.menu-button').attr('aria-expanded','false');}});
$(document).on('click','.skip-link',event=>{event.preventDefault();$('#main').trigger('focus');document.getElementById('main').scrollIntoView();});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
shell();render();
